# -*- coding: utf-8 -*-
"""ExpressionCration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwVL_cqbTAbDZXU6S69bV-Rt-qf-sJYn
"""

import numpy as np

# Define different types of "operations"
def model_linear(X, w, b):
    return np.dot(X, w) + b

def model_poly(X, w, b):
    return np.dot(X**2, w) + b

def model_interaction(X, w, b):
    return w[0] * X[:, 0] * X[:, 1] + b

# Define training function
def train_model(X, y, model_func, input_size, epochs=500, lr=0.01):
    w = np.random.randn(input_size)
    b = np.random.randn()

    for _ in range(epochs):
        preds = model_func(X, w, b)
        error = preds - y
        loss = np.mean(error**2)

        # Basic gradient estimation (finite differences)
        grad_w = 2 * np.dot(X.T, error) / len(X)
        grad_b = 2 * np.mean(error)

        w -= lr * grad_w
        b -= lr * grad_b

    return w, b, loss

# Try all models
def find_best_model(X, y):
    models = {
        "linear": model_linear,
        "polynomial": model_poly,
        "interaction": model_interaction
    }

    results = {}
    for name, func in models.items():
        w, b, loss = train_model(X, y, func, X.shape[1])
        results[name] = {"weights": w, "bias": b, "loss": loss}

    best = min(results.items(), key=lambda x: x[1]['loss'])
    print(f"Best Model: {best[0]}, Loss: {best[1]['loss']:.4f}")
    return best

import numpy as np
import random
import operator
import math

# --- CONFIGURABLE SETTINGS ---
VARIABLES = ['x0', 'x1']  # Number of variables: 2D inputs like x0, x1
OPERATORS = ['+', '-', '*', '/']
CONSTANTS = [1, 2, 3, 5, 10]

MAX_DEPTH = 3
POPULATION_SIZE = 100
GENERATIONS = 50
MUTATION_RATE = 0.3

# --- NODE STRUCTURE FOR EXPRESSIONS ---
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value  # operator, variable, or constant
        self.left = left
        self.right = right

    def is_leaf(self):
        return not self.left and not self.right

    def __str__(self):
        if self.is_leaf():
            return str(self.value)
        return f"({self.left} {self.value} {self.right})"

# --- RANDOM TREE GENERATION ---
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        # Leaf: either a variable or constant
        if random.random() < 0.5:
            return Node(random.choice(VARIABLES))
        else:
            return Node(random.choice(CONSTANTS))
    else:
        op = random.choice(OPERATORS)
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1))

# --- TREE EVALUATION ---
def safe_div(x, y):
    try:
        return x / y if abs(y) > 1e-6 else 1.0
    except:
        return 1.0

OP_FUNC = {
    '+': operator.add,
    '-': operator.sub,
    '*': operator.mul,
    '/': safe_div,
}

def evaluate_tree(node, variables):
    if node.value in VARIABLES:
        return variables[int(node.value[1:])]
    elif node.value in OPERATORS:
        left = evaluate_tree(node.left, variables)
        right = evaluate_tree(node.right, variables)
        return OP_FUNC[node.value](left, right)
    else:
        return float(node.value)

# --- FITNESS FUNCTION ---
def compute_mse(tree, X, y):
    errors = []
    for xi, yi in zip(X, y):
        try:
            y_pred = evaluate_tree(tree, xi)
            errors.append((y_pred - yi) ** 2)
        except:
            errors.append(1e6)
    return np.mean(errors)

# --- MUTATION ---
def mutate(tree, depth=0):
    if random.random() < MUTATION_RATE:
        return generate_random_tree(depth)
    elif not tree.is_leaf():
        return Node(tree.value, mutate(tree.left, depth + 1), mutate(tree.right, depth + 1))
    else:
        return tree

# --- MAIN EVOLUTION LOOP ---
def evolve(X, y):
    population = [generate_random_tree() for _ in range(POPULATION_SIZE)]

    for generation in range(GENERATIONS):
        scored = [(tree, compute_mse(tree, X, y)) for tree in population]
        scored.sort(key=lambda x: x[1])
        best_tree, best_score = scored[0]

        print(f"Generation {generation}: Best MSE = {best_score:.4f} | Expr: {best_tree}")

        # Elitism + mutation
        top_k = [t for t, s in scored[:10]]
        new_population = top_k[:]

        while len(new_population) < POPULATION_SIZE:
            parent = random.choice(top_k)
            child = mutate(parent)
            new_population.append(child)

        population = new_population

    return best_tree

# --- EXAMPLE USAGE ---
if __name__ == "__main__":
    # Example: y = x0 + 2*x1
    X = np.array([
        [1, 2],
        [2, 1],
        [3, 2],
        [4, 3]
    ])
    y = np.array([
        5, 4, 7, 10  # True relationship: x0 + 2*x1
    ])

    best = evolve(X, y)
    print("\n✅ Final Best Expression:", best)

import numpy as np
import random
import operator
import math
import copy

# --- CONFIGURABLE SETTINGS ---
VARIABLES = ['x0', 'x1']
BINARY_OPS = ['+', '-', '*', '/']
UNARY_OPS = ['sin', 'cos', 'log', 'exp', 'sqrt']
ALL_OPS = BINARY_OPS + UNARY_OPS

MAX_DEPTH = 4
POPULATION_SIZE = 150
GENERATIONS = 100
MUTATION_RATE = 0.3
CROSSOVER_RATE = 0.5

# --- NODE STRUCTURE ---
class Node:
    def __init__(self, value, left=None, right=None):  # right is unused for unary ops
        self.value = value
        self.left = left
        self.right = right

    def is_leaf(self):
        return not self.left and not self.right

    def is_unary(self):
        return self.value in UNARY_OPS

    def copy(self):
        return copy.deepcopy(self)

    def __str__(self):
        if self.is_leaf():
            return str(self.value)
        elif self.is_unary():
            return f"{self.value}({self.left})"
        return f"({self.left} {self.value} {self.right})"

# --- TREE GENERATION ---
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        if random.random() < 0.5:
            return Node(random.choice(VARIABLES))
        else:
            return Node(round(random.uniform(-10, 10), 2))
    else:
        op = random.choice(ALL_OPS)
        if op in UNARY_OPS:
            return Node(op, generate_random_tree(depth + 1))
        else:
            return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1))

# --- OP FUNCTIONS ---
def safe_div(x, y):
    return x / y if abs(y) > 1e-6 else 1.0

def safe_log(x):
    return math.log(abs(x) + 1e-6)

def safe_sqrt(x):
    return math.sqrt(abs(x))

OP_FUNC = {
    '+': operator.add,
    '-': operator.sub,
    '*': operator.mul,
    '/': safe_div,
    'sin': math.sin,
    'cos': math.cos,
    'log': safe_log,
    'exp': math.exp,
    'sqrt': safe_sqrt
}

def evaluate_tree(node, variables):
    if node.value in VARIABLES:
        return variables[int(node.value[1:])]
    elif node.value in ALL_OPS:
        if node.is_unary():
            val = evaluate_tree(node.left, variables)
            return OP_FUNC[node.value](val)
        else:
            left = evaluate_tree(node.left, variables)
            right = evaluate_tree(node.right, variables)
            return OP_FUNC[node.value](left, right)
    else:
        return float(node.value)

# --- FITNESS ---
def compute_mse(tree, X, y):
    errors = []
    for xi, yi in zip(X, y):
        try:
            y_pred = evaluate_tree(tree, xi)
            if math.isnan(y_pred) or math.isinf(y_pred):
                y_pred = 1e6
            errors.append((y_pred - yi) ** 2)
        except:
            errors.append(1e6)
    return np.mean(errors)

# --- MUTATION ---
def mutate(tree, depth=0):
    if random.random() < MUTATION_RATE:
        return generate_random_tree(depth)
    elif not tree.is_leaf():
        if tree.is_unary():
            return Node(tree.value, mutate(tree.left, depth + 1))
        else:
            return Node(tree.value, mutate(tree.left, depth + 1), mutate(tree.right, depth + 1))
    else:
        return tree

# --- CROSSOVER ---
def random_subtree(node):
    if node.is_leaf() or random.random() < 0.2:
        return node
    elif node.is_unary():
        return random.choice([node, node.left])
    else:
        return random.choice([node, node.left, node.right])

def crossover(tree1, tree2):
    t1 = tree1.copy()
    t2 = tree2.copy()

    # Pick random subtrees
    sub1 = random_subtree(t1)
    sub2 = random_subtree(t2)

    # Swap values
    sub1.value, sub2.value = sub2.value, sub1.value
    sub1.left, sub2.left = sub2.left, sub1.left
    sub1.right, sub2.right = sub2.right, sub1.right

    return t1

# --- EVOLUTION ---
def evolve(X, y):
    population = [generate_random_tree() for _ in range(POPULATION_SIZE)]

    for generation in range(GENERATIONS):
        scored = [(tree, compute_mse(tree, X, y)) for tree in population]
        scored.sort(key=lambda x: x[1])
        best_tree, best_score = scored[0]

        print(f"Gen {generation:02d} | MSE = {best_score:.4f} | Expr: {best_tree}")

        # Elitism + breeding
        top_k = [t for t, _ in scored[:10]]
        new_population = top_k[:]

        while len(new_population) < POPULATION_SIZE:
            if random.random() < CROSSOVER_RATE:
                parent1 = random.choice(top_k)
                parent2 = random.choice(top_k)
                child = crossover(parent1, parent2)
            else:
                parent = random.choice(top_k)
                child = mutate(parent)
            new_population.append(child)

        population = new_population

    return best_tree

# --- USAGE ---
if __name__ == "__main__":
    # Example: y = x0 + 2*x1
    X = np.array([[1, 2], [2, 1], [3, 2], [4, 3]])
    y = np.array([5, 4, 7, 10])  # target: x0 + 2*x1

    best = evolve(X, y)
    print("\n✅ Best Final Expression:", best)

import numpy as np
import random
import operator
import math
import copy

# --- CONFIG ---
VARIABLES = ['x0', 'x1']
BINARY_OPS = ['+', '-', '*', '/']
UNARY_OPS = ['sin', 'cos', 'log', 'exp', 'sqrt', 'abs', 'tan', 'floor', 'ceil', 'neg']
ALL_OPS = BINARY_OPS + UNARY_OPS

MAX_DEPTH = 20
POPULATION_SIZE = 100
GENERATIONS = 200
MUTATION_RATE = 0.3
CROSSOVER_RATE = 0.5
COMPLEXITY_PENALTY = 0.01  # alpha: weight for complexity penalty

# --- NODE STRUCTURE ---
class Node:
    def __init__(self, value, left=None, right=None):  # right unused for unary
        self.value = value
        self.left = left
        self.right = right

    def is_leaf(self):
        return not self.left and not self.right

    def is_unary(self):
        return self.value in UNARY_OPS

    def copy(self):
        return copy.deepcopy(self)

    def __str__(self):
        if self.is_leaf():
            return str(self.value)
        elif self.is_unary():
            return f"{self.value}({self.left})"
        return f"({self.left} {self.value} {self.right})"

# --- TREE GENERATION ---
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        if random.random() < 0.5:
            return Node(random.choice(VARIABLES))
        else:
            return Node(round(random.uniform(-10, 10), 2))
    else:
        op = random.choice(ALL_OPS)
        if op in UNARY_OPS:
            return Node(op, generate_random_tree(depth + 1))
        else:
            return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1))

# --- OPERATION MAP ---
def safe_div(x, y): return x / y if abs(y) > 1e-6 else 1.0
def safe_log(x): return math.log(abs(x) + 1e-6)
def safe_sqrt(x): return math.sqrt(abs(x))
def safe_tan(x): return math.tan(x) if abs(x) < math.pi / 2 else 0
def safe_exp(x): return math.exp(x) if x < 100 else 1e6

OP_FUNC = {
    '+': operator.add,
    '-': operator.sub,
    '*': operator.mul,
    '/': safe_div,
    'sin': math.sin,
    'cos': math.cos,
    'log': safe_log,
    'exp': safe_exp,
    'sqrt': safe_sqrt,
    'abs': abs,
    'tan': safe_tan,
    'floor': math.floor,
    'ceil': math.ceil,
    'neg': lambda x: -x
}

def evaluate_tree(node, variables):
    try:
        if node.value in VARIABLES:
            return variables[int(node.value[1:])]
        elif node.value in ALL_OPS:
            if node.is_unary():
                val = evaluate_tree(node.left, variables)
                return OP_FUNC[node.value](val)
            else:
                left = evaluate_tree(node.left, variables)
                right = evaluate_tree(node.right, variables)
                return OP_FUNC[node.value](left, right)
        else:
            return float(node.value)
    except:
        return 1e6  # fallback on error

# --- TREE METRICS ---
def tree_size(node):
    if node.is_leaf():
        return 1
    elif node.is_unary():
        return 1 + tree_size(node.left)
    return 1 + tree_size(node.left) + tree_size(node.right)

# --- FITNESS ---
def compute_fitness(tree, X, y):
    errors = []
    for xi, yi in zip(X, y):
        y_pred = evaluate_tree(tree, xi)
        if math.isnan(y_pred) or math.isinf(y_pred):
            y_pred = 1e6
        errors.append((y_pred - yi) ** 2)

    mse = np.mean(errors)
    complexity = tree_size(tree)
    fitness = mse + COMPLEXITY_PENALTY * complexity
    return fitness

# --- MUTATION ---
def mutate(tree, depth=0):
    if random.random() < MUTATION_RATE:
        return generate_random_tree(depth)
    elif not tree.is_leaf():
        if tree.is_unary():
            return Node(tree.value, mutate(tree.left, depth + 1))
        else:
            return Node(tree.value, mutate(tree.left, depth + 1), mutate(tree.right, depth + 1))
    else:
        return tree

# --- CROSSOVER ---
def random_subtree(node):
    if node.is_leaf() or random.random() < 0.2:
        return node
    elif node.is_unary():
        return random.choice([node, node.left])
    else:
        return random.choice([node, node.left, node.right])

def crossover(tree1, tree2):
    t1 = tree1.copy()
    t2 = tree2.copy()
    sub1 = random_subtree(t1)
    sub2 = random_subtree(t2)
    sub1.value, sub2.value = sub2.value, sub1.value
    sub1.left, sub2.left = sub2.left, sub1.left
    sub1.right, sub2.right = sub2.right, sub1.right
    return t1

# --- EVOLUTION ---
def evolve(X, y):
    population = [generate_random_tree() for _ in range(POPULATION_SIZE)]

    for generation in range(GENERATIONS):
        scored = [(tree, compute_fitness(tree, X, y)) for tree in population]
        scored.sort(key=lambda x: x[1])
        best_tree, best_score = scored[0]

        print(f"Gen {generation:02d} | Score = {best_score:.4f} | Expr: {best_tree}")

        top_k = [t for t, _ in scored[:10]]
        new_population = top_k[:]

        while len(new_population) < POPULATION_SIZE:
            if random.random() < CROSSOVER_RATE:
                parent1 = random.choice(top_k)
                parent2 = random.choice(top_k)
                child = crossover(parent1, parent2)
            else:
                parent = random.choice(top_k)
                child = mutate(parent)
            new_population.append(child)

        population = new_population

    return best_tree

# --- RUNNING THE MODEL ---
if __name__ == "__main__":
    # Target: y = x0^2 + 3 * sin(x1)
    X = np.array([[1, 0], [2, math.pi / 2], [3, math.pi], [4, 3 * math.pi / 2], [5, 2 * math.pi]])
    y = np.array([x[0] ** 2 + 3 * math.sin(x[1]) for x in X])

    best = evolve(X, y)
    print("\n✅ Best Final Expression:", best)

import math
import random
import numpy as np

# Define function set
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 4
POPULATION_SIZE = 150
GENERATIONS = 150
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5
MAX_VAL = 1e6  # clamp values to avoid overflow

# Clamp function
def evaluate_safe(val):
    try:
        if math.isnan(val) or math.isinf(val):
            return 1.0
        return max(-MAX_VAL, min(MAX_VAL, val))
    except:
        return 1.0

# Node definition
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return evaluate_safe(x[self.value])
            elif self.value == '+':
                return evaluate_safe(self.left.evaluate(x) + self.right.evaluate(x))
            elif self.value == '-':
                return evaluate_safe(self.left.evaluate(x) - self.right.evaluate(x))
            elif self.value == '*':
                return evaluate_safe(self.left.evaluate(x) * self.right.evaluate(x))
            elif self.value == '/':
                denominator = self.right.evaluate(x)
                return evaluate_safe(self.left.evaluate(x) / denominator if abs(denominator) > 1e-6 else 1.0)
            elif self.value == 'sin':
                return evaluate_safe(math.sin(self.left.evaluate(x)))
            elif self.value == 'cos':
                return evaluate_safe(math.cos(self.left.evaluate(x)))
            elif self.value == 'exp':
                return evaluate_safe(math.exp(self.left.evaluate(x)))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return evaluate_safe(math.log1p(abs(val)))
            else:
                return evaluate_safe(float(self.value))
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        elif self.value in ['sin', 'cos', 'exp', 'log']:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

# Random expression tree
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1))
    else:
        return Node(op, generate_random_tree(depth + 1))

# Mutation
def mutate(node, depth=0):
    if depth >= MAX_DEPTH:
        return node
    if random.random() < MUTATION_RATE:
        return generate_random_tree(depth)
    new_node = node.copy()
    if new_node.left:
        new_node.left = mutate(new_node.left, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, depth + 1)
    return new_node

# Subtree Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy

# Fitness
def fitness(individual, data):
    errors = []
    for x, y in data:
        try:
            pred = individual.evaluate(x)
            error = (pred - y) ** 2
            if math.isnan(error) or math.isinf(error) or error > 1e12:
                error = 1e6  # penalty
        except:
            error = 1e6
        errors.append(error)
    return sum(errors) / len(errors)

# Tournament selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Generate data
def generate_data():
    data = []
    for _ in range(100):
        x0 = random.uniform(0, 10)
        x1 = random.uniform(0, 10)
        y = math.sin(x0) + math.log1p(x1)
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Evolution
def evolve(data):
    population = [generate_random_tree() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:02d} | Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            print("⚠️  Plateau detected: refreshing half of population.")
            population = population[:ELITISM] + [generate_random_tree() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)
        population = new_population

    return population[0]

# Run
if __name__ == "__main__":
    data = generate_data()
    best = evolve(data)
    print("\n✅ Final Best Expression:", best.to_string())

import math
import random
import numpy as np

# Constants
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 150
GENERATIONS = 150
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Node class
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denominator = self.right.evaluate(x)
                return self.left.evaluate(x) / denominator if abs(denominator) > 1e-6 else 1.0
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(self.left.evaluate(x))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        elif self.value in ['sin', 'cos', 'exp', 'log']:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()

        # Constant folding
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        # Identity simplifications
        if self.value == '+':
            if isinstance(self.left.value, (int, float)) and self.left.value == 0:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '*':
            if isinstance(self.left.value, (int, float)) and self.left.value == 0 or \
               isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return Node(0)
            if isinstance(self.left.value, (int, float)) and self.left.value == 1:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left
        elif self.value == '-':
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '/':
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left

        return self

# Tree generator
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Mutation
def mutate(node, depth=0):
    if random.random() < MUTATION_RATE:
        return generate_random_tree(depth).simplify()
    new_node = node.copy()
    if new_node.left:
        new_node.left = mutate(new_node.left, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Fitness function
def fitness(individual, data):
    errors = []
    for x, y in data:
        try:
            pred = individual.evaluate(x)
            if abs(pred) > 1e10:  # avoid overflows
                pred = 1e10
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Data generation
def generate_data():
    data = []
    for _ in range(100):
        x0 = random.uniform(0, 10)  # cover one full sine wave cycle
        x1 = random.uniform(0, 10) # 'x1': x1
        y =3*x0**2 - 2*x1 + 1
        data.append(({'x0': x0,'x1': x1}, y))  # use only x0
    return data

# Evolution process
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:02d} | Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            print("⚠️ Plateau detected: refreshing half of population.")
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)
        population = new_population

    return population[0]

# Run
if __name__ == "__main__":
    data = generate_data()
    best = evolve(data)
    print("\n✅ Final Best Expression:", best.to_string())

import math
import random
import numpy as np

# Constants
OPERATORS = ['+', '-', '*', '/', '^', 'sin', 'cos', 'exp', 'log']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 150
GENERATIONS = 150
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Node class
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denominator = self.right.evaluate(x)
                return self.left.evaluate(x) / denominator if abs(denominator) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                if abs(base) > 1e6 or abs(exp) > 100: return 1.0  # prevent overflows
                return math.pow(base, exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                val = self.left.evaluate(x)
                return math.exp(val) if val < 100 else 1e6
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except Exception:
            return 1.0  # safe fallback

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        elif self.value in ['sin', 'cos', 'exp', 'log']:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()

        # Constant folding
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        # Identity simplifications
        if self.value == '+':
            if isinstance(self.left.value, (int, float)) and self.left.value == 0: return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 0: return self.left
        elif self.value == '-':
            if isinstance(self.right.value, (int, float)) and self.right.value == 0: return self.left
        elif self.value == '*':
            if (isinstance(self.left.value, (int, float)) and self.left.value == 0) or \
               (isinstance(self.right.value, (int, float)) and self.right.value == 0): return Node(0)
            if isinstance(self.left.value, (int, float)) and self.left.value == 1: return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 1: return self.left
        elif self.value == '/':
            if isinstance(self.right.value, (int, float)) and self.right.value == 1: return self.left
        elif self.value == '^':
            if isinstance(self.right.value, (int, float)):
                if self.right.value == 1: return self.left
                if self.right.value == 0: return Node(1)

        return self

# Tree generator
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Mutation
def mutate(node, depth=0):
    if random.random() < MUTATION_RATE:
        return generate_random_tree(depth).simplify()
    new_node = node.copy()
    if new_node.left:
        new_node.left = mutate(new_node.left, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Fitness function
def fitness(individual, data):
    errors = []
    for x, y in data:
        try:
            pred = individual.evaluate(x)
            pred = max(min(pred, 1e6), -1e6)  # clamp
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Data generation
def generate_data():
    data = []
    for _ in range(100):
        x0 = random.uniform(0, 10)
        x1 = random.uniform(0, 10)
        y = 3 * x0 ** 2 - 2 * x1 + 1
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Evolution process
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:02d} | 📉 Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            print("⚠️ Plateau detected: refreshing half of population.")
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)
        population = new_population

    return population[0]

# Run
if __name__ == "__main__":
    data = generate_data()
    best = evolve(data)
    print("\n✅ Final Best Expression:", best.to_string())

import math
import random
import numpy as np

# Function and Variable Sets
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POP_SIZE = 150
GENERATIONS = 150
TOURNAMENT_SIZE = 7
MUTATION_RATE = 0.2
ELITISM = 5
OVERFLOW_LIMIT = 1e6
COMPLEXITY_PENALTY = 1e-3  # Penalize complex trees

# Expression Tree Node
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                val = self.left.evaluate(x)
                return math.exp(val) if val < 100 else OVERFLOW_LIMIT
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        elif self.value in ['sin', 'cos', 'exp', 'log']:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()

        # Constant folding
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        # Unary folding
        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        # Algebraic simplification
        if self.value == '+':
            if isinstance(self.left.value, (int, float)) and self.left.value == 0:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '*':
            if isinstance(self.left.value, (int, float)) and self.left.value == 0 or \
               isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return Node(0)
            if isinstance(self.left.value, (int, float)) and self.left.value == 1:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left
        elif self.value == '-':
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '/':
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left

        return self

    def complexity(self):
        c = 1
        if self.left:
            c += self.left.complexity()
        if self.right:
            c += self.right.complexity()
        return c

# Tree Generator
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 3))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Smarter Mutation
def mutate(node, depth=0):
    if random.random() < MUTATION_RATE:
        if isinstance(node.value, (int, float)):
            # tweak constant
            return Node(round(node.value + random.uniform(-1, 1), 3))
        return generate_random_tree(depth).simplify()
    new_node = node.copy()
    if new_node.left:
        new_node.left = mutate(new_node.left, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, depth + 1)
    return new_node.simplify()

# Subtree Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Fitness with Complexity Penalty
def fitness(individual, data):
    errors = []
    for x, y in data:
        try:
            pred = individual.evaluate(x)
            pred = max(min(pred, OVERFLOW_LIMIT), -OVERFLOW_LIMIT)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    mse = sum(errors) / len(errors)
    penalty = individual.complexity() * COMPLEXITY_PENALTY
    return mse + penalty

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Data Generator
def generate_data():
    data = []
    for _ in range(100):
        x0 = random.uniform(0, 10)
        x1 = random.uniform(0, 10)
        y = 3 * x0 ** 2 - 2 * x1 + 1
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Evolution
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POP_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:02d} | Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            print("⚠️ Plateau: Reinitializing half the population.")
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POP_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POP_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)
        population = new_population

    return population[0]

# Run
if __name__ == "__main__":
    data = generate_data()
    best = evolve(data)
    print("\n✅ Best Expression:", best.to_string())

import math
import random
import numpy as np
from copy import deepcopy

# Constants
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 300
GENERATIONS = 150
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.3
ELITISM = 5
GRADIENT_MUTATION_RATE = 0.1  # chance to use derivative-based mutation

# Node definition
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denominator = self.right.evaluate(x)
                return self.left.evaluate(x) / denominator if abs(denominator) > 1e-6 else 1.0
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(self.left.evaluate(x))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        elif self.value in ['sin', 'cos', 'exp', 'log']:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()

        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        # Simplification rules
        if self.value == '+':
            if isinstance(self.left.value, (int, float)) and self.left.value == 0:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '*':
            if any(isinstance(v.value, (int, float)) and v.value == 0 for v in [self.left, self.right]):
                return Node(0)
            if isinstance(self.left.value, (int, float)) and self.left.value == 1:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left
        elif self.value == '-':
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '/':
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left

        return self

    def differentiate(self, var):
        """Symbolic partial derivative"""
        if self.value == var:
            return Node(1)
        elif self.value in VARIABLES:
            return Node(0)
        elif isinstance(self.value, (int, float)):
            return Node(0)

        u = self.left
        v = self.right

        if self.value == '+':
            return Node('+', u.differentiate(var), v.differentiate(var))
        elif self.value == '-':
            return Node('-', u.differentiate(var), v.differentiate(var))
        elif self.value == '*':
            return Node('+',
                        Node('*', u.differentiate(var), v.copy()),
                        Node('*', u.copy(), v.differentiate(var)))
        elif self.value == '/':
            numerator = Node('-', Node('*', u.differentiate(var), v.copy()),
                                  Node('*', u.copy(), v.differentiate(var)))
            denominator = Node('*', v.copy(), v.copy())
            return Node('/', numerator, denominator)
        elif self.value == 'sin':
            return Node('*', Node('cos', u.copy()), u.differentiate(var))
        elif self.value == 'cos':
            return Node('*', Node('*', Node(-1), Node('sin', u.copy())), u.differentiate(var))
        elif self.value == 'exp':
            return Node('*', Node('exp', u.copy()), u.differentiate(var))
        elif self.value == 'log':
            return Node('/', u.differentiate(var), u.copy())

        return Node(0)

# Tree generation
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Mutation
def mutate(node, depth=0):
    if random.random() < MUTATION_RATE:
        return generate_random_tree(depth).simplify()
    new_node = node.copy()
    if new_node.left:
        new_node.left = mutate(new_node.left, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, depth + 1)
    return new_node.simplify()

# Gradient-assisted mutation
def gradient_mutate(node):
    var = random.choice(VARIABLES)
    grad = node.differentiate(var).simplify()
    return grad if grad else node

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Fitness
def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = max(min(pred, 1e10), -1e10)  # clip overflow
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Data
def generate_data():
    data = []
    for _ in range(100):
        x0 = random.uniform(0, 10)
        x1 = random.uniform(0, 10)
        y = 3*x0**2 - 2*x1 + 1
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Evolution
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:02d} | Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            print("⚠️ Plateau detected: refreshing half of population.")
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            if random.random() < GRADIENT_MUTATION_RATE:
                individual = select(population, scores)
                new_population.append(gradient_mutate(individual).simplify())
            else:
                parent1 = select(population, scores)
                parent2 = select(population, scores)
                child = crossover(parent1, parent2)
                child = mutate(child)
                new_population.append(child)
        population = new_population

    return population[0]

# Run
if __name__ == "__main__":
    data = generate_data()
    best = evolve(data)
    print("\n✅ Final Best Expression:", best.to_string())

import math
import random
import numpy as np

# Configuration
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 100
GENERATIONS = 100
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Expression Node
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()

        # Constant folding
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        # Simplify known identities
        if self.value == '+':
            if isinstance(self.left.value, (int, float)) and self.left.value == 0:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '*':
            if any(isinstance(child.value, (int, float)) and child.value == 0 for child in [self.left, self.right]):
                return Node(0)
            if isinstance(self.left.value, (int, float)) and self.left.value == 1:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left
        elif self.value == '-':
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '/':
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left

        return self

# Tree generation
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Mutation
def mutate(node, depth=0):
    if random.random() < MUTATION_RATE:
        return generate_random_tree(depth).simplify()
    new_node = node.copy()
    if new_node.left:
        new_node.left = mutate(new_node.left, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Fitness
def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Benchmark Suite
def get_benchmark_function(name):
    if name == 'linear_1':
        return lambda x: x['x0'] + x['x1']
    elif name == 'linear_2':
        return lambda x: 2 * x['x0'] - 3 * x['x1']
    elif name == 'linear_bias':
        return lambda x: x['x0'] + 5
    elif name == 'mean':
        return lambda x: (x['x0'] + x['x1']) / 2
    elif name == 'diff':
        return lambda x: x['x0'] - x['x1']
    elif name == 'square_sum':
        return lambda x: x['x0'] ** 2 + x['x1'] ** 2
    elif name == 'poly_1':
        return lambda x: 3 * x['x0'] ** 2 - 2 * x['x1'] + 1
    elif name == 'sinlog':
        return lambda x: math.sin(x['x0']) + math.log1p(x['x1'])
    elif name == 'exp_decay':
        return lambda x: math.exp(-x['x0']) * x['x1']
    elif name == 'rat':
        return lambda x: (x['x0'] + 1) / (x['x1'] + 1)
    elif name == 'osc1':
        return lambda x: math.sin(x['x0']) * math.cos(x['x1'])
    elif name == 'exp_poly':
        return lambda x: math.exp(x['x0'] + x['x1'] ** 2)
    elif name == 'log_exp':
        return lambda x: math.log1p(math.exp(x['x0'] + x['x1']))
    elif name == 'multi_1':
        return lambda x: x['x0'] ** 3 + x['x1'] ** 3 - 3 * x['x0'] * x['x1']
    elif name == 'crazy_combo':
        return lambda x: math.sin(x['x0'] ** 2 + math.log1p(x['x1']))
    else:
        raise ValueError("Unknown benchmark function")

# Data generator
def generate_data(func_name, size=1000):
    f = get_benchmark_function(func_name)
    data = []
    for _ in range(size):
        x0 = random.uniform(0.1, 5)
        x1 = random.uniform(0.1, 5)
        y = f({'x0': x0, 'x1': x1})
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Evolutionary Process
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:03d} | Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            print("⚠️ Plateau detected — refreshing half population")
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)
        population = new_population

    return population[0]

# Run
if __name__ == "__main__":
    func_name = "mean"  # change to test different functions
    data = generate_data(func_name)
    best = evolve(data)
    print("\n✅ Final Best Expression:", best.to_string())
    print('initail expression: ',get_benchmark_function(func_name))

import math
import random
import numpy as np

# Configuration
OPERATORS = ['+', '-', '*', '/', '^', 'sin', 'cos', 'exp', 'log']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 100
GENERATIONS = 100
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Expression Node
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                try:
                    if base < 0 and int(exp) == exp:
                        return math.pow(abs(base), exp) * (-1 if int(exp) % 2 else 1)
                    return math.pow(base, exp)
                except:
                    return 1.0
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()

        # Constant folding
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self

        # Simplify known identities
        if self.value == '+':
            if isinstance(self.left.value, (int, float)) and self.left.value == 0:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '*':
            if any(isinstance(child.value, (int, float)) and child.value == 0 for child in [self.left, self.right]):
                return Node(0)
            if isinstance(self.left.value, (int, float)) and self.left.value == 1:
                return self.right
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left
        elif self.value == '-':
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return self.left
        elif self.value == '/':
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left
        elif self.value == '^':
            if isinstance(self.right.value, (int, float)) and self.right.value == 1:
                return self.left
            if isinstance(self.right.value, (int, float)) and self.right.value == 0:
                return Node(1)

        return self

# Tree generation
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Mutation
def mutate(node, depth=0):
    if random.random() < MUTATION_RATE:
        return generate_random_tree(depth).simplify()
    new_node = node.copy()
    if new_node.left:
        new_node.left = mutate(new_node.left, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Fitness
def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Benchmark Suite
def get_benchmark_function(name):
    if name == 'square_sum':
        return lambda x: x['x0']**2 + x['x1']**2
    elif name == 'mean':
        return lambda x: (x['x0'] + x['x1']) / 2
    elif name == 'linear':
        return lambda x: x['x0'] + x['x1']
    else:
        raise ValueError("Unknown benchmark function")

# Data generator
def generate_data(func_name, size=10000):
    f = get_benchmark_function(func_name)
    data = []
    for _ in range(size):
        x0 = random.uniform(0.1, 5)
        x1 = random.uniform(0.1, 5)
        y = f({'x0': x0, 'x1': x1})
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Evolutionary Process
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:03d} | Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            print("⚠️ Plateau detected — refreshing half population")
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)
        population = new_population

    return population[0]

# Power Operator Test
if __name__ == "__main__":
    # Simple test: x0^2 + x1^2
    print("=== Power Operator Test ===")
    tree = Node('+', Node('^', Node('x0'), Node(2)), Node('^', Node('x1'), Node(2)))
    print("Expression:", tree.to_string())
    x = {'x0': 3, 'x1': 4}
    print("Eval (x0=3, x1=4):", tree.evaluate(x))  # Expect 25

    # Full evolution test
    print("\n=== Evolving Expression for: square_sum ===")
    data = generate_data('mean')
    best = evolve(data)
    print("\n✅ Final Best Expression:", best.to_string())

"""# Best Code Advanced

"""

import math
import random
import numpy as np
import matplotlib.pyplot as plt

# Configuration
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 100
GENERATIONS = 100
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Expression Node
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        return self

# Tree Utilities
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Gradient utilities
def find_constants(node):
    constants = []
    def recurse(n):
        if isinstance(n.value, (int, float)):
            constants.append(n)
        if n.left:
            recurse(n.left)
        if n.right:
            recurse(n.right)
    recurse(node)
    return constants

def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

def nudge_constants(node, data, epsilon=1e-4, step=0.1):
    constants = find_constants(node)
    for c in constants:
        orig = c.value
        c.value = orig + epsilon
        err1 = fitness(node, data)
        c.value = orig - epsilon
        err2 = fitness(node, data)
        grad = (err1 - err2) / (2 * epsilon)
        c.value = orig - step * grad
    return node.simplify()

def smart_structure_mutation(node):
    insert = Node(random.choice(['+', '*']), node.copy(), Node(random.choice(VARIABLES)))
    return insert.simplify()

def mutate(node, data=None, depth=0):
    if random.random() < MUTATION_RATE:
        if random.random() < 0.5:
            return generate_random_tree(depth).simplify()
        else:
            return smart_structure_mutation(node)
    new_node = node.copy()
    if data is not None:
        new_node = nudge_constants(new_node, data)
    if new_node.left:
        new_node.left = mutate(new_node.left, data, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, data, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Benchmark and Data
def get_benchmark_function(name):
    if name == 'mean':
        return lambda x: (x['x0'] + x['x1']) / 2
    else:
        raise ValueError("Unknown benchmark function")

def generate_data(func_name, size=100):
    f = get_benchmark_function(func_name)
    data = []
    for _ in range(size):
        x0 = random.uniform(0.1, 5)
        x1 = random.uniform(0.1, 5)
        y = f({'x0': x0, 'x1': x1})
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Visualizer
def visualize_tree(node, depth=0, prefix=""):
    if node is not None:
        print("    " * depth + prefix + str(node.value))
        if node.left:
            visualize_tree(node.left, depth + 1, "L: ")
        if node.right:
            visualize_tree(node.right, depth + 1, "R: ")

# Evolution

def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:03d} | Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child, data)
            new_population.append(child)
        population = new_population

    return population[0]

if __name__ == '__main__':
    data = generate_data('mean')
    best = evolve(data)
    print("\n✅ Final Expression:", best.to_string())
    visualize_tree(best)

"""# More simply expressions

"""

pip install sympy

import math
import random
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

# Configuration
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 100
GENERATIONS = 100
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Expression Node
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def to_sympy(self):
        if self.value in VARIABLES:
            return sp.Symbol(self.value)
        elif isinstance(self.value, (int, float)):
            return sp.Float(self.value)
        elif self.value == '+':
            return self.left.to_sympy() + self.right.to_sympy()
        elif self.value == '-':
            return self.left.to_sympy() - self.right.to_sympy()
        elif self.value == '*':
            return self.left.to_sympy() * self.right.to_sympy()
        elif self.value == '/':
            return self.left.to_sympy() / self.right.to_sympy()
        elif self.value == '^':
            return self.left.to_sympy() ** self.right.to_sympy()
        elif self.value == 'sin':
            return sp.sin(self.left.to_sympy())
        elif self.value == 'cos':
            return sp.cos(self.left.to_sympy())
        elif self.value == 'exp':
            return sp.exp(self.left.to_sympy())
        elif self.value == 'log':
            return sp.log(self.left.to_sympy())
        else:
            raise ValueError(f"Unknown node value: {self.value}")

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        return self

# Tree Utilities
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Gradient utilities
def find_constants(node):
    constants = []
    def recurse(n):
        if isinstance(n.value, (int, float)):
            constants.append(n)
        if n.left:
            recurse(n.left)
        if n.right:
            recurse(n.right)
    recurse(node)
    return constants

def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

def nudge_constants(node, data, epsilon=1e-4, step=0.1):
    constants = find_constants(node)
    for c in constants:
        orig = c.value
        c.value = orig + epsilon
        err1 = fitness(node, data)
        c.value = orig - epsilon
        err2 = fitness(node, data)
        grad = (err1 - err2) / (2 * epsilon)
        c.value = orig - step * grad
    return node.simplify()

def smart_structure_mutation(node):
    if random.random() < 0.5:
        return Node('+', node.copy(), Node(round(random.uniform(-5, 5), 2))).simplify()
    else:
        return Node(random.choice(['+', '*']), node.copy(), Node(random.choice(VARIABLES))).simplify()

def mutate(node, data=None, depth=0):
    if random.random() < MUTATION_RATE:
        if random.random() < 0.5:
            return generate_random_tree(depth).simplify()
        else:
            return smart_structure_mutation(node)
    new_node = node.copy()
    if data is not None:
        new_node = nudge_constants(new_node, data)
    if new_node.left:
        new_node.left = mutate(new_node.left, data, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, data, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Benchmark and Data
def get_benchmark_function(name):
    if name == 'mean':
        return lambda x: (x['x0'] + x['x1']) / 2
    else:
        raise ValueError("Unknown benchmark function")

def generate_data(func_name, size=100):
    f = get_benchmark_function(func_name)
    data = []
    for _ in range(size):
        x0 = random.uniform(0.1, 5)
        x1 = random.uniform(0.1, 5)
        y = f({'x0': x0, 'x1': x1})
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Visualizer
def visualize_tree(node, depth=0, prefix=""):
    if node is not None:
        print("    " * depth + prefix + str(node.value))
        if node.left:
            visualize_tree(node.left, depth + 1, "L: ")
        if node.right:
            visualize_tree(node.right, depth + 1, "R: ")

# Evolution
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:03d} | Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child, data)
            new_population.append(child)
        population = new_population

    return population[0]

if __name__ == '__main__':
    data = generate_data('mean')
    best = evolve(data)
    print("\n✅ Final Expression:", best.to_string())
    visualize_tree(best)
    sym_expr = best.to_sympy()
    print("\n🧠 SymPy Expression:", sym_expr)
    print("📄 LaTeX:", sp.latex(sym_expr))

import math
import random
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

# Configuration
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 150
GENERATIONS = 100
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Expression Node
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def to_sympy(self):
        if self.value in VARIABLES:
            return sp.Symbol(self.value)
        elif isinstance(self.value, (int, float)):
            return sp.Float(self.value)
        elif self.value == '+':
            return self.left.to_sympy() + self.right.to_sympy()
        elif self.value == '-':
            return self.left.to_sympy() - self.right.to_sympy()
        elif self.value == '*':
            return self.left.to_sympy() * self.right.to_sympy()
        elif self.value == '/':
            return self.left.to_sympy() / self.right.to_sympy()
        elif self.value == '^':
            return self.left.to_sympy() ** self.right.to_sympy()
        elif self.value == 'sin':
            return sp.sin(self.left.to_sympy())
        elif self.value == 'cos':
            return sp.cos(self.left.to_sympy())
        elif self.value == 'exp':
            return sp.exp(self.left.to_sympy())
        elif self.value == 'log':
            return sp.log(self.left.to_sympy() + 1)

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        return self

# Tree Utilities
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Gradient utilities
def find_constants(node):
    constants = []
    def recurse(n):
        if isinstance(n.value, (int, float)):
            constants.append(n)
        if n.left:
            recurse(n.left)
        if n.right:
            recurse(n.right)
    recurse(node)
    return constants

def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

def nudge_constants(node, data, epsilon=1e-4, step=0.1):
    constants = find_constants(node)
    for c in constants:
        orig = c.value
        c.value = orig + epsilon
        err1 = fitness(node, data)
        c.value = orig - epsilon
        err2 = fitness(node, data)
        grad = (err1 - err2) / (2 * epsilon)
        c.value = orig - step * grad
    return node.simplify()

def smart_structure_mutation(node):
    insert = Node('+', node.copy(), Node(round(random.uniform(-5, 5), 2)))  # Bias injection
    return insert.simplify()

def mutate(node, data=None, depth=0):
    if random.random() < MUTATION_RATE:
        if random.random() < 0.5:
            return generate_random_tree(depth).simplify()
        else:
            return smart_structure_mutation(node)
    new_node = node.copy()
    if data is not None:
        new_node = nudge_constants(new_node, data)
    if new_node.left:
        new_node.left = mutate(new_node.left, data, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, data, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Benchmark and Data
def get_benchmark_function(name):
    if name == 'mean':
        return lambda x: (x['x0'] + x['x1']) / 2
    elif name == 'product':
        return lambda x: x['x0'] * x['x1']
    elif name == 'sine':
        return lambda x: math.sin(x['x0']) + math.cos(x['x1'])
    elif name == 'logsum':
        return lambda x: math.log(x['x0'] + x['x1'] + 1)
    elif name == 'exp':
        return lambda x: math.exp(0.1 * x['x0']) + math.exp(0.1 * x['x1'])
    else:
        raise ValueError("Unknown benchmark function")

def generate_data(func_name, size=100):
    f = get_benchmark_function(func_name)
    data = []
    for _ in range(size):
        x0 = random.uniform(0.1, 5)
        x1 = random.uniform(0.1, 5)
        y = f({'x0': x0, 'x1': x1})
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Visualizer
def visualize_tree(node, depth=0, prefix=""):
    if node is not None:
        print("    " * depth + prefix + str(node.value))
        if node.left:
            visualize_tree(node.left, depth + 1, "L: ")
        if node.right:
            visualize_tree(node.right, depth + 1, "R: ")

# Evolution
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0
    best_expr = None

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            best_expr = population[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child, data)
            new_population.append(child)
        population = new_population

    return best_expr, best_fitness

if __name__ == '__main__':
    benchmarks = ['mean', 'product', 'sine', 'logsum', 'exp']
    for name in benchmarks:
        print(f"\n--- Benchmark: {name.upper()} ---")
        best = None
        best_score = float('inf')
        for i in range(3):
            data = generate_data(name)
            expr, score = evolve(data)
            if score < best_score:
                best = expr
                best_score = score
        print(f"✅ Best Expression: {best.to_string()}")
        print(f"📉 MSE: {best_score:.6f}")
        print(f"🧮 SymPy: {best.to_sympy()}")
        print(f"📄 LaTeX: {sp.latex(best.to_sympy())}")
        visualize_tree(best)