# -*- coding: utf-8 -*-
"""neuro_symbol_network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ecjQU6m-8y1KWJCnZjp18MoDASt1vVhV

# neuro_symbol_network
"""

import math
import random
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

# Configuration
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 100
GENERATIONS = 100
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Expression Node
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def to_sympy(self):
        if self.value in VARIABLES:
            return sp.Symbol(self.value)
        elif isinstance(self.value, (int, float)):
            return sp.Float(self.value)
        elif self.value == '+':
            return self.left.to_sympy() + self.right.to_sympy()
        elif self.value == '-':
            return self.left.to_sympy() - self.right.to_sympy()
        elif self.value == '*':
            return self.left.to_sympy() * self.right.to_sympy()
        elif self.value == '/':
            return self.left.to_sympy() / self.right.to_sympy()
        elif self.value == '^':
            return self.left.to_sympy() ** self.right.to_sympy()
        elif self.value == 'sin':
            return sp.sin(self.left.to_sympy())
        elif self.value == 'cos':
            return sp.cos(self.left.to_sympy())
        elif self.value == 'exp':
            return sp.exp(self.left.to_sympy())
        elif self.value == 'log':
            return sp.log(self.left.to_sympy())
        else:
            raise ValueError(f"Unknown node value: {self.value}")

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        return self

# Tree Utilities
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Gradient utilities
def find_constants(node):
    constants = []
    def recurse(n):
        if isinstance(n.value, (int, float)):
            constants.append(n)
        if n.left:
            recurse(n.left)
        if n.right:
            recurse(n.right)
    recurse(node)
    return constants

def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

def nudge_constants(node, data, epsilon=1e-4, step=0.1):
    constants = find_constants(node)
    for c in constants:
        orig = c.value
        c.value = orig + epsilon
        err1 = fitness(node, data)
        c.value = orig - epsilon
        err2 = fitness(node, data)
        grad = (err1 - err2) / (2 * epsilon)
        c.value = orig - step * grad
    return node.simplify()

def smart_structure_mutation(node):
    if random.random() < 0.5:
        return Node('+', node.copy(), Node(round(random.uniform(-5, 5), 2))).simplify()
    else:
        return Node(random.choice(['+', '*']), node.copy(), Node(random.choice(VARIABLES))).simplify()

def mutate(node, data=None, depth=0):
    if random.random() < MUTATION_RATE:
        if random.random() < 0.5:
            return generate_random_tree(depth).simplify()
        else:
            return smart_structure_mutation(node)
    new_node = node.copy()
    if data is not None:
        new_node = nudge_constants(new_node, data)
    if new_node.left:
        new_node.left = mutate(new_node.left, data, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, data, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Benchmark and Data
def get_benchmark_function(name):
    if name == 'mean':
        return lambda x: (x['x0'] + x['x1']) / 2
    else:
        raise ValueError("Unknown benchmark function")

def generate_data(func_name, size=100):
    f = get_benchmark_function(func_name)
    data = []
    for _ in range(size):
        x0 = random.uniform(0.1, 5)
        x1 = random.uniform(0.1, 5)
        y = f({'x0': x0, 'x1': x1})
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Visualizer
def visualize_tree(node, depth=0, prefix=""):
    if node is not None:
        print("    " * depth + prefix + str(node.value))
        if node.left:
            visualize_tree(node.left, depth + 1, "L: ")
        if node.right:
            visualize_tree(node.right, depth + 1, "R: ")

# Evolution
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:03d} | Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child, data)
            new_population.append(child)
        population = new_population

    return population[0]

if __name__ == '__main__':
    data = generate_data('mean')
    best = evolve(data)
    print("\n✅ Final Expression:", best.to_string())
    visualize_tree(best)
    sym_expr = best.to_sympy()
    print("\n🧠 SymPy Expression:", sym_expr)
    print("📄 LaTeX:", sp.latex(sym_expr))

import math
import random
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

# Configuration
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 150
GENERATIONS = 50
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Expression Node
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def to_sympy(self):
        if self.value in VARIABLES:
            return sp.Symbol(self.value)
        elif isinstance(self.value, (int, float)):
            return sp.Float(self.value)
        elif self.value == '+':
            return self.left.to_sympy() + self.right.to_sympy()
        elif self.value == '-':
            return self.left.to_sympy() - self.right.to_sympy()
        elif self.value == '*':
            return self.left.to_sympy() * self.right.to_sympy()
        elif self.value == '/':
            return self.left.to_sympy() / self.right.to_sympy()
        elif self.value == '^':
            return self.left.to_sympy() ** self.right.to_sympy()
        elif self.value == 'sin':
            return sp.sin(self.left.to_sympy())
        elif self.value == 'cos':
            return sp.cos(self.left.to_sympy())
        elif self.value == 'exp':
            return sp.exp(self.left.to_sympy())
        elif self.value == 'log':
            return sp.log(self.left.to_sympy() + 1)

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        return self

# Tree Utilities
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Gradient utilities
def find_constants(node):
    constants = []
    def recurse(n):
        if isinstance(n.value, (int, float)):
            constants.append(n)
        if n.left:
            recurse(n.left)
        if n.right:
            recurse(n.right)
    recurse(node)
    return constants

def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

def nudge_constants(node, data, epsilon=1e-4, step=0.1):
    constants = find_constants(node)
    for c in constants:
        orig = c.value
        c.value = orig + epsilon
        err1 = fitness(node, data)
        c.value = orig - epsilon
        err2 = fitness(node, data)
        grad = (err1 - err2) / (2 * epsilon)
        c.value = orig - step * grad
    return node.simplify()

def smart_structure_mutation(node):
    insert = Node('+', node.copy(), Node(round(random.uniform(-5, 5), 2)))  # Bias injection
    return insert.simplify()

def mutate(node, data=None, depth=0):
    if random.random() < MUTATION_RATE:
        if random.random() < 0.5:
            return generate_random_tree(depth).simplify()
        else:
            return smart_structure_mutation(node)
    new_node = node.copy()
    if data is not None:
        new_node = nudge_constants(new_node, data)
    if new_node.left:
        new_node.left = mutate(new_node.left, data, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, data, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Benchmark and Data
def get_benchmark_function(name):
    if name == 'mean':
        return lambda x: (x['x0'] + x['x1']) / 2
    elif name == 'product':
        return lambda x: x['x0'] * x['x1']
    elif name == 'sine':
        return lambda x: math.sin(x['x0']) + math.cos(x['x1'])
    elif name == 'logsum':
        return lambda x: math.log(x['x0'] + x['x1'] + 1)
    elif name == 'exp':
        return lambda x: math.exp(0.1 * x['x0']) + math.exp(0.1 * x['x1'])
    else:
        raise ValueError("Unknown benchmark function")

def generate_data(func_name, size=100):
    f = get_benchmark_function(func_name)
    data = []
    for _ in range(size):
        x0 = random.uniform(0.1, 5)
        x1 = random.uniform(0.1, 5)
        y = f({'x0': x0, 'x1': x1})
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Visualizer
def visualize_tree(node, depth=0, prefix=""):
    if node is not None:
        print("    " * depth + prefix + str(node.value))
        if node.left:
            visualize_tree(node.left, depth + 1, "L: ")
        if node.right:
            visualize_tree(node.right, depth + 1, "R: ")

# Evolution
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0
    best_expr = None

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            best_expr = population[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child, data)
            new_population.append(child)
        population = new_population

    return best_expr, best_fitness

if __name__ == '__main__':
    benchmarks = ['mean', 'product', 'sine', 'logsum', 'exp']
    for name in benchmarks:
        print(f"\n--- Benchmark: {name.upper()} ---")
        data = generate_data(name)
        expr, score = evolve(data)
        print(f"✅ Best Expression: {expr.to_string()}")
        print(f"📉 MSE: {score:.6f}")
        print(f"🧮 SymPy: {expr.to_sympy()}")
        print(f"📄 LaTeX: {sp.latex(expr.to_sympy())}")
        visualize_tree(expr)

"""# **Start**"""

class SymbolicNeuron:
    def __init__(self, tree=None):
        self.tree = tree if tree else generate_random_tree().simplify()

    def forward(self, x):
        return self.tree.evaluate(x)

    def mutate(self, data):
        self.tree = mutate(self.tree, data)

    def optimize_constants(self, data):
        self.tree = nudge_constants(self.tree, data)

    def expression(self):
        return self.tree.to_string()

    def visualize(self):
        visualize_tree(self.tree)


if __name__ == "__main__":
    data = generate_data('mean', size=20)
    neuron = SymbolicNeuron()

    print("🔍 Initial expression:", neuron.expression())

    for epoch in range(100):
        neuron.optimize_constants(data)
        neuron.mutate(data)

    print("✅ Final expression:", neuron.expression())
    neuron.visualize()

    # Evaluation
    mse = sum((neuron.forward(x) - y)**2 for x, y in data) / len(data)
    print("📉 MSE:", mse)

import math
import random
import numpy as np
from typing import List

# ---------------------------- Node Class ----------------------------
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if isinstance(self.value, (int, float)):
                return self.value
            elif self.value in x:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
        except:
            return 1.0

    def to_string(self):
        if isinstance(self.value, (int, float)) or self.value in ['x0', 'x1']:
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()
        if self.left and self.right:
            if isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
                try:
                    return Node(self.evaluate({}))
                except:
                    pass
        return self

# ---------------------------- Tree Utilities ----------------------------
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 4


def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-3, 3), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# ---------------------------- Evolutionary Symbolic Regression ----------------------------
POPULATION_SIZE = 150
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5


def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)


def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]


def crossover(t1, t2):
    def get_random_node(node):
        nodes = []

        def collect(n):
            if n is None: return
            nodes.append(n)
            if n.left: collect(n.left)
            if n.right: collect(n.right)

        collect(node)
        return random.choice(nodes)

    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()


def mutate(node):
    if random.random() < MUTATION_RATE:
        return generate_random_tree()
    node = node.copy()
    if node.left:
        node.left = mutate(node.left)
    if node.right:
        node.right = mutate(node.right)
    return node.simplify()


def evolve_symbolic_expression(input_vars, data, generations=30):
    population = [generate_random_tree() for _ in range(POPULATION_SIZE)]
    for gen in range(generations):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        print(f"  Gen {gen+1:03d} | Best Score: {ranked[0][1]:.6f}")
        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)
        population = new_population
    return population[0]

# ---------------------------- Symbolic Neuron Layer ----------------------------
class SymbolicNeuron:
    def __init__(self, expression=None):
        self.expression = expression

    def evaluate(self, x):
        return self.expression.evaluate(x)

    def __str__(self):
        return self.expression.to_string()


class SymbolicLayer:
    def __init__(self, input_vars: List[str], num_neurons: int):
        self.input_vars = input_vars
        self.num_neurons = num_neurons
        self.neurons = [SymbolicNeuron() for _ in range(num_neurons)]

    def evaluate(self, x):
        return [neuron.evaluate(x) for neuron in self.neurons]

    def evolve(self, data, generations=30):
        for i, neuron in enumerate(self.neurons):
            print(f"\n🔄 Evolving neuron {i+1}/{self.num_neurons}")
            scalar_data = [(x, y[i]) for x, y in data]  # Fix: train on individual neuron target
            best_expr = evolve_symbolic_expression(self.input_vars, scalar_data, generations)
            neuron.expression = best_expr

# ---------------------------- Vector Data Generator ----------------------------
def generate_vector_data(funcs, size=100):
    data = []
    for _ in range(size):
        x0 = random.uniform(-3, 3)
        x1 = random.uniform(-3, 3)
        x = {'x0': x0, 'x1': x1}
        y = [f(x) for f in funcs]
        data.append((x, y))
    return data

# ---------------------------- Example ----------------------------
if __name__ == '__main__':
    # 4 symbolic neurons each learning different behavior
    target_funcs = [
        lambda x: x['x0'] + x['x1'],
        lambda x: x['x0'] * x['x1'],
        lambda x: x['x0'] ** 2 + x['x1'] * 3 + 5,
        lambda x: math.sin(x['x1'])
    ]

    data = generate_vector_data(target_funcs, size=100)
    symbolic_layer = SymbolicLayer(input_vars=['x0', 'x1'], num_neurons=4)
    symbolic_layer.evolve(data, generations=100)

    print("\n🧠 Symbolic Layer Expressions:")
    for i, neuron in enumerate(symbolic_layer.neurons):
        print(f"Neuron {i+1}: {neuron}")

import math
import random
import hashlib
from abc import ABC, abstractmethod

# --- Safe math operations ---
def safe_div(x, y):
    return x / y if abs(y) > 1e-6 else 1.0

def safe_log(x):
    return math.log(abs(x)) if abs(x) > 1e-6 else 0.0

def safe_sqrt(x):
    return math.sqrt(abs(x))

# --- Expression Tree Base ---
class ExprNode(ABC):
    @abstractmethod
    def evaluate(self, x): pass

    @abstractmethod
    def to_string(self): pass

    @abstractmethod
    def simplify(self): pass

    @abstractmethod
    def clone(self): pass

    @abstractmethod
    def get_hash(self): pass

# --- Terminal Node (constants and variables) ---
class TerminalNode(ExprNode):
    def __init__(self, value, is_variable=False):
        self.value = value
        self.is_variable = is_variable

    def evaluate(self, x):
        return x if self.is_variable else self.value

    def to_string(self):
        return 'x' if self.is_variable else str(self.value)

    def simplify(self):
        return self

    def clone(self):
        return TerminalNode(self.value, self.is_variable)

    def get_hash(self):
        return f"VAR" if self.is_variable else f"CONST:{self.value}"

# --- Operator Node (internal function nodes) ---
class OperatorNode(ExprNode):
    def __init__(self, op, children):
        self.op = op
        self.children = children

    def evaluate(self, x):
        args = [c.evaluate(x) for c in self.children]
        try:
            return self.apply_op(args)
        except:
            return 0.0

    def apply_op(self, args):
        if self.op == '+': return args[0] + args[1]
        if self.op == '-': return args[0] - args[1]
        if self.op == '*': return args[0] * args[1]
        if self.op == '/': return safe_div(args[0], args[1])
        if self.op == '^': return args[0] ** args[1]
        if self.op == 'sin': return math.sin(args[0])
        if self.op == 'cos': return math.cos(args[0])
        if self.op == 'log': return safe_log(args[0])
        if self.op == 'exp': return math.exp(args[0])
        return 0.0

    def to_string(self):
        if self.op in ['+', '-', '*', '/', '^']:
            return f"({self.children[0].to_string()} {self.op} {self.children[1].to_string()})"
        else:
            return f"{self.op}({self.children[0].to_string()})"

    def simplify(self):
        simplified_children = [c.simplify() for c in self.children]

        # Constant folding
        if all(isinstance(c, TerminalNode) and not c.is_variable for c in simplified_children):
            val = self.apply_op([c.value for c in simplified_children])
            return TerminalNode(val)

        return OperatorNode(self.op, simplified_children)

    def clone(self):
        return OperatorNode(self.op, [c.clone() for c in self.children])

    def get_hash(self):
        child_hashes = ':'.join([c.get_hash() for c in self.children])
        return f"{self.op}({child_hashes})"

# --- Symbolic Neuron Wrapper ---
class SymbolicNeuron:
    def __init__(self, expr_tree):
        self.expr_tree = expr_tree
        self.bias = random.uniform(-1, 1)

    def forward(self, x):
        return self.expr_tree.evaluate(x) + self.bias

    def simplify(self):
        self.expr_tree = self.expr_tree.simplify()

    def to_string(self):
        return f"{self.expr_tree.to_string()} + {self.bias:.3f}"

    def get_hash(self):
        return hashlib.md5((self.expr_tree.get_hash() + f"|{self.bias:.3f}").encode()).hexdigest()

# --- Test the engine with an example expression ---
if __name__ == "__main__":
    # Expression: sin(x) + 3
    expr = OperatorNode('+', [
        OperatorNode('sin', [TerminalNode(0, is_variable=True)]),
        TerminalNode(3.0)
    ])

    neuron = SymbolicNeuron(expr)

    for x in range(-3, 4):
        print(f"x={x} => output={neuron.forward(x):.4f}")

    print("Simplified:", neuron.simplify() or neuron.to_string())
    print("Neuron hash:", neuron.get_hash())

import math
import random
import numpy as np

# --- Node Definitions --- #
class Node:
    def evaluate(self, x):
        raise NotImplementedError

    def __str__(self):
        raise NotImplementedError

    def simplify(self):
        return self

    def get_constants(self):
        return []

    def set_constants(self, values):
        pass

class Const(Node):
    def __init__(self, value):
        self.value = float(value)

    def evaluate(self, x):
        return self.value

    def __str__(self):
        return f"{self.value:.3f}"

    def get_constants(self):
        return [self.value]

    def set_constants(self, values):
        self.value = values[0]

class Var(Node):
    def evaluate(self, x):
        return x

    def __str__(self):
        return "x"

class Add(Node):
    def __init__(self, left, right):
        self.left = left
        self.right = right

    def evaluate(self, x):
        return self.left.evaluate(x) + self.right.evaluate(x)

    def __str__(self):
        return f"({self.left} + {self.right})"

    def simplify(self):
        left = self.left.simplify()
        right = self.right.simplify()
        if isinstance(left, Const) and isinstance(right, Const):
            return Const(left.value + right.value)
        return Add(left, right)

    def get_constants(self):
        return self.left.get_constants() + self.right.get_constants()

    def set_constants(self, values):
        n = len(self.left.get_constants())
        self.left.set_constants(values[:n])
        self.right.set_constants(values[n:])

class Mul(Node):
    def __init__(self, left, right):
        self.left = left
        self.right = right

    def evaluate(self, x):
        return self.left.evaluate(x) * self.right.evaluate(x)

    def __str__(self):
        return f"({self.left} * {self.right})"

    def simplify(self):
        left = self.left.simplify()
        right = self.right.simplify()
        if isinstance(left, Const) and isinstance(right, Const):
            return Const(left.value * right.value)
        return Mul(left, right)

    def get_constants(self):
        return self.left.get_constants() + self.right.get_constants()

    def set_constants(self, values):
        n = len(self.left.get_constants())
        self.left.set_constants(values[:n])
        self.right.set_constants(values[n:])

class Sin(Node):
    def __init__(self, child):
        self.child = child

    def evaluate(self, x):
        return math.sin(self.child.evaluate(x))

    def __str__(self):
        return f"sin({self.child})"

    def simplify(self):
        simplified_child = self.child.simplify()
        if isinstance(simplified_child, Const):
            return Const(math.sin(simplified_child.value))
        return Sin(simplified_child)

    def get_constants(self):
        return self.child.get_constants()

    def set_constants(self, values):
        self.child.set_constants(values)

# --- Symbolic Neuron Wrapper --- #
class SymbolicNeuron:
    def __init__(self, expression: Node):
        self.expression = expression

    def predict(self, X):
        return np.array([self.safe_eval(xi) for xi in X])

    def safe_eval(self, x):
        try:
            val = self.expression.evaluate(x)
            return val if not math.isnan(val) and not math.isinf(val) else 1e6
        except Exception:
            return 1e6

    def get_constants(self):
        return self.expression.get_constants()

    def set_constants(self, values):
        self.expression.set_constants(values)

    def simplify(self):
        self.expression = self.expression.simplify()

    def __str__(self):
        return str(self.expression)

# --- Loss function --- #
def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# --- Test Expression: sin(x) + 3 --- #
x = Var()
expr = Add(Sin(x), Const(3))

neuron = SymbolicNeuron(expr)

# Dataset: true function is sin(x) + 3
X = np.linspace(-2*np.pi, 2*np.pi, 100)
y_true = np.sin(X) + 3
y_pred = neuron.predict(X)

error = mean_squared_error(y_true, y_pred)

# --- Output --- #
print("Expression:", neuron)
print("Error (MSE):", error)

import math
import random
import numpy as np
from typing import List, Dict
import graphviz

# ---------------------------- Node Class ----------------------------
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x: Dict[str, float]) -> float:
        try:
            if isinstance(self.value, (int, float)):
                return self.value
            elif self.value in x:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log(val) if val > 1e-6 else 0.0
        except:
            return 1.0

    def to_string(self):
        if isinstance(self.value, (int, float)) or self.value in ['x0', 'x1']:
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()
        try:
            if self.left and self.right and all(isinstance(n.value, (int, float)) for n in [self.left, self.right]):
                return Node(self.evaluate({}))
            if self.left and isinstance(self.left.value, (int, float)) and self.value in ['sin', 'cos', 'exp', 'log']:
                return Node(self.evaluate({}))
        except:
            pass
        return self

    def derivative(self, var):
        if isinstance(self.value, (int, float)):
            return Node(0.0)
        elif self.value == var:
            return Node(1.0)
        elif self.value == '+':
            return Node('+', self.left.derivative(var), self.right.derivative(var))
        elif self.value == '-':
            return Node('-', self.left.derivative(var), self.right.derivative(var))
        elif self.value == '*':
            return Node('+', Node('*', self.left.derivative(var), self.right.copy()), Node('*', self.left.copy(), self.right.derivative(var)))
        elif self.value == '/':
            num = Node('-', Node('*', self.left.derivative(var), self.right.copy()), Node('*', self.left.copy(), self.right.derivative(var)))
            den = Node('^', self.right.copy(), Node(2.0))
            return Node('/', num, den)
        elif self.value == '^':
            base, exp = self.left, self.right
            return Node('*', Node('*', Node('^', base.copy(), exp.copy()), Node('log', base.copy())),
                        exp.derivative(var))
        elif self.value == 'sin':
            return Node('*', Node('cos', self.left.copy()), self.left.derivative(var))
        elif self.value == 'cos':
            return Node('*', Node('*', Node(-1.0), Node('sin', self.left.copy())), self.left.derivative(var))
        elif self.value == 'exp':
            return Node('*', Node('exp', self.left.copy()), self.left.derivative(var))
        elif self.value == 'log':
            return Node('/', self.left.derivative(var), self.left.copy())
        return Node(0.0)

    def visualize(self, dot=None, parent=None, name='expr'):
        if dot is None:
            dot = graphviz.Digraph(name)
        uid = str(id(self))
        dot.node(uid, str(self.value))
        if parent:
            dot.edge(str(parent), uid)
        if self.left:
            self.left.visualize(dot, uid)
        if self.right:
            self.right.visualize(dot, uid)
        return dot

    def complexity(self):
        if self.left is None and self.right is None:
            return 1
        left_complexity = self.left.complexity() if self.left else 0
        right_complexity = self.right.complexity() if self.right else 0
        return 1 + left_complexity + right_complexity

# ---------------------------- Tree Utilities ----------------------------
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 4

def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-3, 3), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# ---------------------------- Evolution ----------------------------
POP_SIZE = 100
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5
LAMBDA_COMPLEXITY = 1e-4

def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    error = sum(errors) / len(errors)
    return error + LAMBDA_COMPLEXITY * ind.complexity()

def select(pop, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(pop) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return pop[best]

def crossover(t1, t2):
    def get_nodes(node):
        nodes = []
        def collect(n):
            if n:
                nodes.append(n)
                collect(n.left)
                collect(n.right)
        collect(node)
        return nodes
    t1_copy, t2_copy = t1.copy(), t2.copy()
    n1 = random.choice(get_nodes(t1_copy))
    n2 = random.choice(get_nodes(t2_copy))
    if random.random() < 0.5:
        n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

def mutate(tree):
    if random.random() < MUTATION_RATE:
        return generate_random_tree()
    tree = tree.copy()
    nodes = []
    def collect(n):
        if n:
            nodes.append(n)
            collect(n.left)
            collect(n.right)
    collect(tree)
    mut_node = random.choice(nodes)
    if random.random() < 0.5:
        new_sub = generate_random_tree()
        mut_node.value, mut_node.left, mut_node.right = new_sub.value, new_sub.left, new_sub.right
    return tree.simplify()

def evolve_symbolic_expression(data, generations=30):
    population = [generate_random_tree() for _ in range(POP_SIZE)]
    for gen in range(generations):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        print(f"Gen {gen+1:03d} | Best Score: {ranked[0][1]:.6f}")
        new_pop = population[:ELITISM]
        while len(new_pop) < POP_SIZE:
            p1 = select(population, scores)
            p2 = select(population, scores)
            child = crossover(p1, p2)
            child = mutate(child)
            new_pop.append(child)
        population = new_pop
    return population[0]

def test():
    func = lambda x: x['x0'] + x['x1']
    data = []
    for _ in range(100):
        x0 = random.uniform(-3, 3)
        x1 = random.uniform(-3, 3)
        x = {'x0': x0, 'x1': x1}
        y = func(x)
        data.append((x, y))
    best = evolve_symbolic_expression(data, generations=50)
    print("\n🧠 Best Evolved Expression:")
    print(best.to_string())
    best.visualize().render("tree", format="png", cleanup=False)

if __name__ == '__main__':
    test()

# Enhanced Symbolic Regression Engine
import math
import random
import numpy as np
from typing import List
import graphviz

# ---------------------------- Node Class ----------------------------
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if isinstance(self.value, (int, float)):
                return self.value
            elif self.value in x:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log(val) if val > 1e-6 else 0.0
            elif self.value == 'bias':
                return 1.0
        except:
            return 1.0

    def to_string(self):
        if isinstance(self.value, (int, float)) or self.value in ['x0', 'x1']:
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        elif self.value == 'bias':
            return '1.0'
        else:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()
        if self.left and self.right:
            if isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
                try:
                    return Node(self.evaluate({}))
                except:
                    pass
        return self

    def complexity(self):
        count = 1
        if self.left:
            count += self.left.complexity()
        if self.right:
            count += self.right.complexity()
        return count

    def visualize(self, graph=None, prefix=''):
        if graph is None:
            graph = graphviz.Digraph()
        name = prefix + str(id(self))
        graph.node(name, str(self.value))
        if self.left:
            lname = prefix + str(id(self.left))
            graph.edge(name, lname)
            self.left.visualize(graph, prefix)
        if self.right:
            rname = prefix + str(id(self.right))
            graph.edge(name, rname)
            self.right.visualize(graph, prefix)
        return graph

# ---------------------------- Tree Utilities ----------------------------
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
TERMINALS = VARIABLES + ['bias']
MAX_DEPTH = 4


def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        val = random.choice(TERMINALS)
        return Node(val) if isinstance(val, str) else Node(round(random.uniform(-3, 3), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# ---------------------------- Evolutionary Symbolic Regression ----------------------------
POPULATION_SIZE = 100
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5
REGULARIZATION_WEIGHT = 1e-3

def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    mse = sum(errors) / len(errors)
    reg = REGULARIZATION_WEIGHT * ind.complexity()
    return mse + reg


def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]


def crossover(t1, t2):
    def get_random_node(node):
        nodes = []

        def collect(n):
            if n is None: return
            nodes.append(n)
            if n.left: collect(n.left)
            if n.right: collect(n.right)

        collect(node)
        return random.choice(nodes)

    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    if random.random() < 0.5:
        n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()


def mutate(node):
    if random.random() < MUTATION_RATE:
        return generate_random_tree()
    node = node.copy()
    if node.left and random.random() < 0.5:
        node.left = mutate(node.left)
    if node.right and random.random() < 0.5:
        node.right = mutate(node.right)
    return node.simplify()


def evolve_symbolic_expression(input_vars, data, generations=30):
    population = [generate_random_tree() for _ in range(POPULATION_SIZE)]
    for gen in range(generations):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        print(f"  Gen {gen+1:03d} | Best Score: {ranked[0][1]:.6f}")
        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)
        population = new_population
    return population[0]

# ---------------------------- Example Run ----------------------------
def test():
    func = lambda x: x['x0'] ** 2 + 3 * x['x1'] + 5        # [M1]
    data = []
    for _ in range(1000):
        x0 = random.uniform(-3, 3)
        x1 = random.uniform(-3, 3)
        x = {'x0': x0, 'x1': x1}
        y = func(x)
        data.append((x, y))
    best = evolve_symbolic_expression(['x0', 'x1'], data, generations=100)
    print("\n🧠 Best Evolved Expression:")
    print(best.to_string())
    best.visualize().render("tree", format="png", cleanup=False)

if __name__ == '__main__':
    test()

# -------------------- Imports --------------------
import math
import random
from typing import List, Tuple
import numpy as np

# -------------------- Node Class --------------------
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if isinstance(self.value, (int, float)):
                return self.value
            elif self.value in x:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log(val) if val > 1e-6 else 0.0
        except:
            return 1.0

    def to_string(self):
        if isinstance(self.value, (int, float)) or self.value in ['x0', 'x1']:
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def count_nodes(self):
        count = 1
        if self.left:
            count += self.left.count_nodes()
        if self.right:
            count += self.right.count_nodes()
        return count

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()

        # Rule-based simplification
        if self.value == '+' and self.right and self.right.value == 0:
            return self.left
        if self.value == '+' and self.left and self.left.value == 0:
            return self.right
        if self.value == '*' and self.right and self.right.value == 1:
            return self.left
        if self.value == '*' and self.left and self.left.value == 1:
            return self.right
        if self.value == '*' and ((self.left and self.left.value == 0) or (self.right and self.right.value == 0)):
            return Node(0)

        if self.left and self.right:
            if isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
                try:
                    return Node(self.evaluate({}))
                except:
                    pass
        return self

# -------------------- Tree Utilities --------------------
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 4


def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-3, 3), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# -------------------- Evolution --------------------
POP_SIZE = 150
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5
LAMBDA_COMPLEXITY = 0.001


def fitness(ind: Node, data: List[Tuple[dict, float]]):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    mse = sum(errors) / len(errors)
    return mse + LAMBDA_COMPLEXITY * ind.count_nodes()


def select(pop, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(pop) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return pop[best]


def crossover(t1: Node, t2: Node):
    def get_random_node(node):
        nodes = []
        def collect(n):
            if n is None: return
            nodes.append(n)
            if n.left: collect(n.left)
            if n.right: collect(n.right)
        collect(node)
        return random.choice(nodes)

    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()


def mutate(node):
    if random.random() < MUTATION_RATE:
        return generate_random_tree()
    node = node.copy()
    if node.left:
        node.left = mutate(node.left)
    if node.right:
        node.right = mutate(node.right)
    return node.simplify()


def evolve_symbolic_expression(data, generations=50):
    population = [generate_random_tree() for _ in range(POP_SIZE)]
    for gen in range(generations):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        print(f"  Gen {gen+1:03d} | Best Score: {ranked[0][1]:.6f}")
        new_pop = population[:ELITISM]
        while len(new_pop) < POP_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_pop.append(child)
        population = new_pop
    return population[0]

# -------------------- Example Run --------------------
def generate_data(func, size=100):
    data = []
    for _ in range(size):
        x0 = random.uniform(-3, 3)
        x1 = random.uniform(-3, 3)
        x = {'x0': x0, 'x1': x1}
        y = func(x)
        data.append((x, y))
    return data

if __name__ == '__main__':
    target_func = lambda x: x['x0']**2 + 3 * x['x1'] + 5
    data = generate_data(target_func)
    best = evolve_symbolic_expression(data, generations=100)
    print("\n\U0001F9E0 Best Evolved Expression:")
    print(best.to_string())

# Full Generalized Symbolic Regression Engine with Test Harness
import math
import random
import numpy as np
from typing import List, Callable

# ---------------------------- Node Class ----------------------------
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if isinstance(self.value, (int, float)):
                return self.value
            elif self.value in x:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log(val) if val > 1e-6 else 0.0
        except:
            return 1.0

    def to_string(self):
        if isinstance(self.value, (int, float)) or self.value in ['x0', 'x1']:
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def complexity(self):
        c = 1
        if self.left:
            c += self.left.complexity()
        if self.right:
            c += self.right.complexity()
        return c

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()

        # Constant folding
        if self.left and self.right:
            if isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
                try:
                    return Node(self.evaluate({}))
                except:
                    pass

        # Rule-based simplifications
        if self.value == '+' and isinstance(self.right.value, (int, float)) and self.right.value == 0:
            return self.left
        if self.value == '*' and isinstance(self.right.value, (int, float)) and self.right.value == 1:
            return self.left

        return self

# ---------------------------- Tree Utilities ----------------------------
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 4


def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-3, 3), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# ---------------------------- Evolution ----------------------------
POP_SIZE = 150
TOURNAMENT = 5
MUT_RATE = 0.2
ELITISM = 5
LAMBDA_COMPLEXITY = 0.001


def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    mse = sum(errors) / len(errors)
    return mse + LAMBDA_COMPLEXITY * ind.complexity()


def select(pop, scores):
    best = None
    for _ in range(TOURNAMENT):
        i = random.randint(0, len(pop) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return pop[best]


def crossover(t1, t2):
    def get_random_node(node):
        nodes = []

        def collect(n):
            if n is None: return
            nodes.append(n)
            if n.left: collect(n.left)
            if n.right: collect(n.right)

        collect(node)
        return random.choice(nodes)

    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()


def mutate(node):
    if random.random() < MUT_RATE:
        return generate_random_tree()
    node = node.copy()
    if node.left:
        node.left = mutate(node.left)
    if node.right:
        node.right = mutate(node.right)
    return node.simplify()


def evolve_symbolic_expression(data, generations=100):
    population = [generate_random_tree() for _ in range(POP_SIZE)]
    for gen in range(generations):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        print(f"  Gen {gen + 1:03d} | Best Score: {ranked[0][1]:.6f}")
        new_population = population[:ELITISM]
        while len(new_population) < POP_SIZE:
            p1 = select(population, scores)
            p2 = select(population, scores)
            child = crossover(p1, p2)
            child = mutate(child)
            new_population.append(child)
        population = new_population
    return population[0]

# ---------------------------- Benchmark Suite ----------------------------
def generate_data(func: Callable, size=100):
    data = []
    for _ in range(size):
        x0 = random.uniform(-3, 3)
        x1 = random.uniform(-3, 3)
        x = {'x0': x0, 'x1': x1}
        y = func(x)
        data.append((x, y))
    return data


def run_benchmark():
    benchmark_funcs = {
    "[S1] Linear": lambda x: x['x0'] + x['x1'],
    "[S2] Arithmetic": lambda x: x['x0'] * 2 - x['x1'] + 3,
    "[M1] Polynomial": lambda x: x['x0'] ** 2 + 3 * x['x1'] + 5,
    "[M2] Transcendental": lambda x: sin(x['x0']) + log1p(abs(x['x1'])),
    "[H1] Oscillation": lambda x: sin(x['x0'] * x['x1']) + 0.5 * x['x1'],
    "[H2] Composite": lambda x: sin(x['x0']) * exp(x['x1']) + x['x0']**2 - log1p(abs(x['x1'])),
    "[H3] Multi-step": lambda x: exp(sin(x['x0']) + cos(x['x1'])) + tanh(x['x0'] - x['x1'])
    }
    for name, func in benchmark_funcs.items():
        print(f"\n🚀 Benchmark: {name}")
        data = generate_data(func, 100)
        best_expr = evolve_symbolic_expression(data, generations=50)
        print("\n🧠 Best Evolved Expression:")
        print(best_expr.to_string())

# ---------------------------- Run ----------------------------
if __name__ == '__main__':
    run_benchmark()

import random
import math
import copy

# === Expression Node Classes ===
class Expr:
    def evaluate(self, x): raise NotImplementedError()
    def get_constants(self): return []
    def __str__(self): raise NotImplementedError()

class Const(Expr):
    def __init__(self, value): self.value = value
    def evaluate(self, x): return self.value
    def get_constants(self): return [self]
    def __str__(self): return f"{self.value:.3f}"

class Var(Expr):
    def __init__(self, name): self.name = name
    def evaluate(self, x): return x.get(self.name, 0)
    def __str__(self): return self.name

class Op(Expr):
    def __init__(self, op, children): self.op, self.children = op, children
    def evaluate(self, x):
        vals = [c.evaluate(x) for c in self.children]
        try:
            if self.op == '+': return vals[0] + vals[1]
            if self.op == '-': return vals[0] - vals[1]
            if self.op == '*': return vals[0] * vals[1]
            if self.op == '/': return vals[0] / vals[1] if vals[1] != 0 else 1
            if self.op == '^': return vals[0] ** vals[1] if vals[0] >= 0 else 1
            if self.op == 'sin': return math.sin(vals[0])
            if self.op == 'cos': return math.cos(vals[0])
            if self.op == 'exp': return math.exp(vals[0])
            if self.op == 'log': return math.log(vals[0]) if vals[0] > 0 else 0
        except: return 1
    def get_constants(self):
        consts = []
        for c in self.children:
            consts.extend(c.get_constants())
        return consts
    def __str__(self):
        if len(self.children) == 1:
            return f"{self.op}({self.children[0]})"
        return f"({self.children[0]} {self.op} {self.children[1]})"

# === Utility Functions ===
def safe_eval(expr):
    try: return expr.evaluate({'x': 1})
    except: return 0

def mse_loss(expr, data, target_fn):
    return sum((expr.evaluate({'x': x}) - target_fn(x)) ** 2 for x in data) / len(data)

# === Simplifier ===
def simplify_expr(node):
    if isinstance(node, (Const, Var)): return node
    if isinstance(node, Op):
        node.children = [simplify_expr(child) for child in node.children]

        if node.op == '-' and len(node.children) == 1:
            child = node.children[0]
            if isinstance(child, Const): return Const(-child.value)
            if isinstance(child, Op) and child.op == '-': return child.children[0]

        if all(isinstance(c, Const) for c in node.children):
            return Const(safe_eval(node))

        left, right = node.children if len(node.children) == 2 else (None, None)
        if node.op == '+':
            if isinstance(left, Const) and left.value == 0: return right
            if isinstance(right, Const) and right.value == 0: return left
        if node.op == '*':
            if isinstance(left, Const) and left.value == 1: return right
            if isinstance(right, Const) and right.value == 1: return left
            if isinstance(left, Const) and left.value == 0: return Const(0)
            if isinstance(right, Const) and right.value == 0: return Const(0)
        if node.op == '-':
            if isinstance(right, Const) and right.value == 0: return left
            if isinstance(left, Const) and left.value == 0: return Op('-', [right])
        if node.op == '/':
            if isinstance(right, Const) and right.value == 1: return left
        if node.op == '^':
            if isinstance(right, Const) and right.value == 1: return left
            if isinstance(right, Const) and right.value == 0: return Const(1)
            if isinstance(left, Const) and left.value == 0: return Const(0)

    return node

# === Bias Injector ===
def has_constant(node):
    if isinstance(node, Const): return True
    if isinstance(node, Op): return any(has_constant(c) for c in node.children)
    return False

def inject_bias(node, bias_range=(-1, 1)):
    if not has_constant(node):
        bias = Const(random.uniform(*bias_range))
        return Op('+', [node, bias])
    return node

# === Gradient Constant Tuner ===
def tune_constants(expr, data, target_fn, lr=0.01, steps=10):
    constants = expr.get_constants()
    for _ in range(steps):
        grads = []
        baseline_loss = mse_loss(expr, data, target_fn)
        for const in constants:
            original = const.value
            const.value += 1e-4
            perturbed_loss = mse_loss(expr, data, target_fn)
            grad = (perturbed_loss - baseline_loss) / 1e-4
            grads.append(grad)
            const.value = original
        for i, const in enumerate(constants):
            const.value -= lr * grads[i]
    return expr

# === Evolution Example Integration ===
def evolve_population(population, data, target_fn):
    new_pop = []
    for expr in population:
        mutated = mutate(copy.deepcopy(expr))
        simplified = simplify_expr(mutated)
        biased = inject_bias(simplified)
        tuned = tune_constants(biased, data, target_fn)
        new_pop.append(tuned)
    return new_pop

# === Dummy Mutation (replace with real logic) ===
def mutate(expr):
    return expr  # placeholder

# === Example Main Loop ===
def main():
    data = [i / 10 for i in range(-50, 51)]
    target_fn = lambda x: x**2 + 2*x + 1
    population = [Op('+', [Op('*', [Var('x'), Var('x')]), Const(1.0)]) for _ in range(10)]
    for gen in range(10):
        population = evolve_population(population, data, target_fn)
        best = min(population, key=lambda e: mse_loss(e, data, target_fn))
        print(f"Gen {gen}: Best Loss = {mse_loss(best, data, target_fn):.4f}, Expr = {best}")

if __name__ == '__main__':
    main()

