# -*- coding: utf-8 -*-
"""neuro_symbol_network3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DW8z9kjhHRMvq5pRzpzTTSSGh59H4ZSe
"""

import math
import random
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

# Configuration
OPERATORS = ['+', '-', '*', '/', 'sin', 'cos', 'exp', 'log', '^']
VARIABLES = ['x0', 'x1']
MAX_DEPTH = 5
POPULATION_SIZE = 100
GENERATIONS = 100
TOURNAMENT_SIZE = 5
MUTATION_RATE = 0.2
ELITISM = 5

# Expression Node
class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def to_string(self):
        if self.value in VARIABLES or isinstance(self.value, (int, float)):
            return str(self.value)
        elif self.value in ['+', '-', '*', '/', '^']:
            return f'({self.left.to_string()} {self.value} {self.right.to_string()})'
        else:
            return f'{self.value}({self.left.to_string()})'

    def to_sympy(self):
        if self.value in VARIABLES:
            return sp.Symbol(self.value)
        elif isinstance(self.value, (int, float)):
            return sp.Float(self.value)
        elif self.value == '+':
            return self.left.to_sympy() + self.right.to_sympy()
        elif self.value == '-':
            return self.left.to_sympy() - self.right.to_sympy()
        elif self.value == '*':
            return self.left.to_sympy() * self.right.to_sympy()
        elif self.value == '/':
            return self.left.to_sympy() / self.right.to_sympy()
        elif self.value == '^':
            return self.left.to_sympy() ** self.right.to_sympy()
        elif self.value == 'sin':
            return sp.sin(self.left.to_sympy())
        elif self.value == 'cos':
            return sp.cos(self.left.to_sympy())
        elif self.value == 'exp':
            return sp.exp(self.left.to_sympy())
        elif self.value == 'log':
            return sp.log(self.left.to_sympy())
        else:
            raise ValueError(f"Unknown node value: {self.value}")

    def copy(self):
        return Node(self.value,
                    self.left.copy() if self.left else None,
                    self.right.copy() if self.right else None)

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()
        if self.left and self.right and isinstance(self.left.value, (int, float)) and isinstance(self.right.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        if self.left and not self.right and isinstance(self.left.value, (int, float)):
            try:
                return Node(self.evaluate({}))
            except:
                return self
        return self

# Tree Utilities
def generate_random_tree(depth=0):
    if depth >= MAX_DEPTH or (depth > 0 and random.random() < 0.3):
        return Node(random.choice(VARIABLES) if random.random() < 0.7 else round(random.uniform(-5, 5), 2))
    op = random.choice(OPERATORS)
    if op in ['+', '-', '*', '/', '^']:
        return Node(op, generate_random_tree(depth + 1), generate_random_tree(depth + 1)).simplify()
    else:
        return Node(op, generate_random_tree(depth + 1)).simplify()

# Gradient utilities
def find_constants(node):
    constants = []
    def recurse(n):
        if isinstance(n.value, (int, float)):
            constants.append(n)
        if n.left:
            recurse(n.left)
        if n.right:
            recurse(n.right)
    recurse(node)
    return constants

def fitness(ind, data):
    errors = []
    for x, y in data:
        try:
            pred = ind.evaluate(x)
            pred = min(max(pred, -1e10), 1e10)
        except:
            pred = 1.0
        errors.append((pred - y) ** 2)
    return sum(errors) / len(errors)

def nudge_constants(node, data, epsilon=1e-4, step=0.1):
    constants = find_constants(node)
    for c in constants:
        orig = c.value
        c.value = orig + epsilon
        err1 = fitness(node, data)
        c.value = orig - epsilon
        err2 = fitness(node, data)
        grad = (err1 - err2) / (2 * epsilon)
        c.value = orig - step * grad
    return node.simplify()

def smart_structure_mutation(node):
    if random.random() < 0.5:
        return Node('+', node.copy(), Node(round(random.uniform(-5, 5), 2))).simplify()
    else:
        return Node(random.choice(['+', '*']), node.copy(), Node(random.choice(VARIABLES))).simplify()

def mutate(node, data=None, depth=0):
    if random.random() < MUTATION_RATE:
        if random.random() < 0.5:
            return generate_random_tree(depth).simplify()
        else:
            return smart_structure_mutation(node)
    new_node = node.copy()
    if data is not None:
        new_node = nudge_constants(new_node, data)
    if new_node.left:
        new_node.left = mutate(new_node.left, data, depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, data, depth + 1)
    return new_node.simplify()

# Crossover
def get_random_node(node):
    nodes = []
    def collect(n):
        if n is None: return
        nodes.append(n)
        if n.left: collect(n.left)
        if n.right: collect(n.right)
    collect(node)
    return random.choice(nodes)

def crossover(t1, t2):
    t1_copy = t1.copy()
    t2_copy = t2.copy()
    n1 = get_random_node(t1_copy)
    n2 = get_random_node(t2_copy)
    n1.value, n1.left, n1.right = n2.value, n2.left, n2.right
    return t1_copy.simplify()

# Selection
def select(population, scores):
    best = None
    for _ in range(TOURNAMENT_SIZE):
        i = random.randint(0, len(population) - 1)
        if best is None or scores[i] < scores[best]:
            best = i
    return population[best]

# Benchmark and Data
def get_benchmark_function(name):
    if name == 'mean':
        return lambda x: (x['x0'] + x['x1']) / 2
    else:
        raise ValueError("Unknown benchmark function")

def generate_data(func_name, size=100):
    f = get_benchmark_function(func_name)
    data = []
    for _ in range(size):
        x0 = random.uniform(0.1, 5)
        x1 = random.uniform(0.1, 5)
        y = f({'x0': x0, 'x1': x1})
        data.append(({'x0': x0, 'x1': x1}, y))
    return data

# Visualizer
def visualize_tree(node, depth=0, prefix=""):
    if node is not None:
        print("    " * depth + prefix + str(node.value))
        if node.left:
            visualize_tree(node.left, depth + 1, "L: ")
        if node.right:
            visualize_tree(node.right, depth + 1, "R: ")

# Evolution
def evolve(data):
    population = [generate_random_tree().simplify() for _ in range(POPULATION_SIZE)]
    best_fitness = float('inf')
    stagnation = 0

    for gen in range(GENERATIONS):
        scores = [fitness(ind, data) for ind in population]
        ranked = sorted(zip(population, scores), key=lambda x: x[1])
        population = [p for p, _ in ranked]
        scores = [s for _, s in ranked]

        print(f"Gen {gen+1:03d} | Best Score: {scores[0]:.6f} | Expr: {population[0].to_string()}")

        if scores[0] < best_fitness:
            best_fitness = scores[0]
            stagnation = 0
        else:
            stagnation += 1

        if stagnation > 10:
            population = population[:ELITISM] + [generate_random_tree().simplify() for _ in range(POPULATION_SIZE - ELITISM)]
            stagnation = 0
            continue

        new_population = population[:ELITISM]
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population, scores)
            parent2 = select(population, scores)
            child = crossover(parent1, parent2)
            child = mutate(child, data)
            new_population.append(child)
        population = new_population

    return population[0]

if __name__ == '__main__':
    data = generate_data('mean')
    best = evolve(data)
    print("\n✅ Final Expression:", best.to_string())
    visualize_tree(best)
    sym_expr = best.to_sympy()
    print("\n🧠 SymPy Expression:", sym_expr)
    print("📄 LaTeX:", sp.latex(sym_expr))

import math
import sympy as sp

VARIABLES = {'x','y',} #,  'z'

class Node:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

    def is_constant(self):
        return isinstance(self.value, (int, float))

    def count_nodes(self):
        count = 1
        if self.left:
            count += self.left.count_nodes()
        if self.right:
            count += self.right.count_nodes()
        return count

    def depth(self):
        if not self.left and not self.right:
            return 0
        left_depth = self.left.depth() if self.left else 0
        right_depth = self.right.depth() if self.right else 0
        return 1 + max(left_depth, right_depth)


    def evaluate(self, x):
        try:
            if self.value in VARIABLES:
                return x[self.value]
            elif self.value == 'pi':
                return math.pi
            elif self.value == 'e':
                return math.e
            elif self.value == '+':
                return self.left.evaluate(x) + self.right.evaluate(x)
            elif self.value == '-':
                return self.left.evaluate(x) - self.right.evaluate(x)
            elif self.value == '*':
                return self.left.evaluate(x) * self.right.evaluate(x)
            elif self.value == '/':
                denom = self.right.evaluate(x)
                return self.left.evaluate(x) / denom if abs(denom) > 1e-6 else 1.0
            elif self.value == '^':
                base = self.left.evaluate(x)
                exp = self.right.evaluate(x)
                if isinstance(exp, (int, float)) and int(exp) == exp:
                    return math.copysign(math.pow(abs(base), exp), base)
                return math.pow(abs(base), exp)
            elif self.value == 'sin':
                return math.sin(self.left.evaluate(x))
            elif self.value == 'cos':
                return math.cos(self.left.evaluate(x))
            elif self.value == 'exp':
                return math.exp(min(self.left.evaluate(x), 20))
            elif self.value == 'log':
                val = self.left.evaluate(x)
                return math.log1p(abs(val))
            else:
                return float(self.value)
        except:
            return 1.0

    def __str__(self):
        if self.left and self.right:
            return f"({str(self.left)} {self.value} {str(self.right)})"
        elif self.left:
            return f"{self.value}({str(self.left)})"
        else:
            return str(self.value)

    # Optional: clean tree string for developers
    def to_string(self):
        return str(self)


    def to_sympy(self):
        if self.value in VARIABLES:
            return sp.Symbol(self.value)
        elif self.value == 'pi':
            return sp.pi
        elif self.value == 'e':
            return sp.E
        elif self.is_constant():
            return sp.Float(self.value)
        elif self.value == '+':
            return self.left.to_sympy() + self.right.to_sympy()
        elif self.value == '-':
            return self.left.to_sympy() - self.right.to_sympy()
        elif self.value == '*':
            return self.left.to_sympy() * self.right.to_sympy()
        elif self.value == '/':
            return self.left.to_sympy() / self.right.to_sympy()
        elif self.value == '^':
            return self.left.to_sympy() ** self.right.to_sympy()
        elif self.value == 'sin':
            return sp.sin(self.left.to_sympy())
        elif self.value == 'cos':
            return sp.cos(self.left.to_sympy())
        elif self.value == 'exp':
            return sp.exp(self.left.to_sympy())
        elif self.value == 'log':
            return sp.log(self.left.to_sympy())
        else:
            raise ValueError(f"Unknown node value: {self.value}")

    def copy(self):
        return Node(self.value,
                    self.left.copy().simplify() if self.left else None,
                    self.right.copy().simplify() if self.right else None).simplify()

    def simplify(self):
        if self.left:
            self.left = self.left.simplify()
        if self.right:
            self.right = self.right.simplify()

        # Constant folding
        if self.left and self.right and self.left.is_constant() and self.right.is_constant():
            try:
                return Node(self.evaluate({}))
            except:
                return self
        if self.left and not self.right and self.left.is_constant():
            try:
                return Node(self.evaluate({}))
            except:
                return self

        # Rule-based simplification
        if self.value == '+':
            if self.right and self.right.is_constant() and self.right.value == 0:
                return self.left
            if self.left and self.left.is_constant() and self.left.value == 0:
                return self.right

        if self.value == '-':
            if self.right and self.right.is_constant() and self.right.value == 0:
                return self.left

        if self.value == '*':
            if (self.left.is_constant() and self.left.value == 0) or (self.right.is_constant() and self.right.value == 0):
                return Node(0)
            if self.left.is_constant() and self.left.value == 1:
                return self.right
            if self.right.is_constant() and self.right.value == 1:
                return self.left

        if self.value == '/':
            if self.right.is_constant() and self.right.value == 1:
                return self.left

        if self.value == '^':
            if self.right.is_constant() and self.right.value == 1:
                return self.left
            if self.right.is_constant() and self.right.value == 0:
                return Node(1)

        return self

    def differentiate(self, var):
        if self.is_constant() or (self.value not in VARIABLES and not self.left):
            return Node(0).simplify()

        if self.value == var:
            return Node(1).simplify()

        if self.value == '+':
            return Node('+', self.left.differentiate(var), self.right.differentiate(var)).simplify()

        if self.value == '-':
            return Node('-', self.left.differentiate(var), self.right.differentiate(var)).simplify()

        if self.value == '*':
            return Node('+',
                        Node('*', self.left.differentiate(var), self.right.copy()),
                        Node('*', self.left.copy(), self.right.differentiate(var))).simplify()

        if self.value == '/':
            num = Node('-',
                       Node('*', self.left.differentiate(var), self.right.copy()),
                       Node('*', self.left.copy(), self.right.differentiate(var)))
            denom = Node('^', self.right.copy(), Node(2))
            return Node('/', num, denom).simplify()

        if self.value == '^':
            if self.right.is_constant():
                new_exp = Node('-', self.right.copy(), Node(1))
                return Node('*',
                            Node('*', self.right.copy(), Node('^', self.left.copy(), new_exp)),
                            self.left.differentiate(var)).simplify()
            else:
                u = self.left
                v = self.right
                return Node('*',
                            Node('^', u.copy(), v.copy()),
                            Node('+',
                                 Node('*', v.differentiate(var), Node('log', u.copy())),
                                 Node('*', v.copy(), Node('/', u.differentiate(var), u.copy())))).simplify()

        if self.value == 'sin':
            return Node('*', Node('cos', self.left.copy()), self.left.differentiate(var)).simplify()

        if self.value == 'cos':
            return Node('*', Node('*', Node(-1), Node('sin', self.left.copy())), self.left.differentiate(var)).simplify()

        if self.value == 'exp':
            return Node('*', Node('exp', self.left.copy()), self.left.differentiate(var)).simplify()

        if self.value == 'log':
            return Node('/', self.left.differentiate(var), self.left.copy()).simplify()

        return Node(0).simplify()

    def get_node_signatures(self):
        return self._collect_signatures(self)

    def _collect_signatures(self, node):
        if node is None:
            return set()
        sigs = {str(node)}  # Use `node.label`, `node.operator`, etc. as needed
        for child in getattr(node, 'children', []):
            sigs |= self._collect_signatures(child)
        return sigs

    def __eq__(self, other):
        if not isinstance(other, Node):
            return False
        return str(self) == str(other)

    def __hash__(self):
        return hash(str(self))


# Optional: Convert SymPy back to Node
def from_sympy(expr):
    if expr.is_Symbol:
        return Node(str(expr))
    elif expr.is_Number:
        return Node(float(expr))
    elif expr.func == sp.Add:
        return Node('+', from_sympy(expr.args[0]), from_sympy(expr.args[1]))
    elif expr.func == sp.Mul:
        return Node('*', from_sympy(expr.args[0]), from_sympy(expr.args[1]))
    elif expr.func == sp.Pow:
        return Node('^', from_sympy(expr.args[0]), from_sympy(expr.args[1]))
    elif expr.func == sp.sin:
        return Node('sin', from_sympy(expr.args[0]))
    elif expr.func == sp.cos:
        return Node('cos', from_sympy(expr.args[0]))
    elif expr.func == sp.exp:
        return Node('exp', from_sympy(expr.args[0]))
    elif expr.func == sp.log:
        return Node('log', from_sympy(expr.args[0]))
    elif expr.func == sp.NegativeOne:
        return Node(-1)
    elif expr.func == sp.Mul and expr.args[0] == -1:
        return Node('*', Node(-1), from_sympy(expr.args[1]))
    elif expr.func == sp.Div:
        return Node('/', from_sympy(expr.args[0]), from_sympy(expr.args[1]))
    else:
        raise ValueError(f"Unsupported SymPy expression: {expr}")

import random

OPERATORS = ['+', '-', '*', '/', '^']
UNARY_FUNCTIONS = ['sin', 'cos', 'log', 'exp']
TERMINALS = list(VARIABLES) + [0.0, 1.0, -1.0]  # Add more constants as needed

def generate_random_tree(depth=0, max_depth=4):
    # Leaf node (terminal or constant)
    if depth >= max_depth or (depth > 0 and random.random() < 0.2):
        terminal = random.choice(TERMINALS + [round(random.uniform(-5.0, 5.0), 2)])
        return Node(terminal)

    node_type = random.choices(
        ['binary', 'unary', 'constant'],
        weights=[0.6, 0.3, 0.1]
    )[0]

    if node_type == 'binary':
        op = random.choice(OPERATORS)
        left = generate_random_tree(depth + 1, max_depth)
        right = generate_random_tree(depth + 1, max_depth)
        return Node(op, left, right)

    elif node_type == 'unary':
        func = random.choice(UNARY_FUNCTIONS)
        child = generate_random_tree(depth + 1, max_depth)
        return Node(func, child)

    else:  # constant node
        return Node(round(random.uniform(-10.0, 10.0), 2))

def mutate(node, max_depth=5, mutation_rate=0.1, current_depth=0):

    if current_depth >= max_depth:
        return node.copy()

    # 1. Decide if we should mutate at this node
    if random.random() < mutation_rate:
        mutation_type = random.choices(
            ['subtree', 'constant_perturb', 'operator_swap', 'variable_swap', 'insert_bias', 'negate_subtree'],
            weights=[0.2, 0.3, 0.2, 0.15, 0.1, 0.05]
        )[0]

        if mutation_type == 'subtree':
            # Replace the entire subtree with a new random one
            return generate_random_tree(depth=current_depth, max_depth=max_depth)

        elif mutation_type == 'constant_perturb' and node.is_constant():
            new_node = node.copy()
            new_node.value += round(random.uniform(-1.0, 1.0), 3)
            return new_node

        elif mutation_type == 'operator_swap' and node.value in ['+', '-', '*', '/', '^']:
            new_node = node.copy()
            new_node.value = random.choice(['+', '-', '*', '/', '^'])
            return new_node

        elif mutation_type == 'variable_swap' and node.value in VARIABLES:
            return Node(random.choice(list(VARIABLES - {node.value})))

        elif mutation_type == 'insert_bias':
            # Add a small constant to the current expression (simulates +b)
            return Node('+', node.copy(), Node(round(random.uniform(-2.0, 2.0), 3)))

        elif mutation_type == 'negate_subtree':
            return Node('*', Node(-1), node.copy())

    # 2. Recurse into children
    new_node = node.copy()
    if new_node.left:
        new_node.left = mutate(new_node.left, max_depth, mutation_rate, current_depth + 1)
    if new_node.right:
        new_node.right = mutate(new_node.right, max_depth, mutation_rate, current_depth + 1)
    return new_node.simplify()


def get_all_subtrees(node, allow_constants=False, min_depth=1):
    subtrees = []

    def collect(n, depth):
        if n is None:
            return
        if depth >= min_depth:
            if allow_constants or not n.is_constant():
                subtrees.append(n)
        if n.left:
            collect(n.left, depth + 1)
        if n.right:
            collect(n.right, depth + 1)

    collect(node, 0)
    return subtrees

def safe_replace(parent, target, replacement):
    """
    Replaces `target` subtree in `parent` with `replacement`.
    """
    if parent is target:
        return replacement.copy()

    new_node = Node(parent.value)
    if parent.left:
        new_node.left = safe_replace(parent.left, target, replacement)
    if parent.right:
        new_node.right = safe_replace(parent.right, target, replacement)
    return new_node

def crossover(parent1, parent2, max_attempts=10):
    for _ in range(max_attempts):
        p1 = parent1.copy()
        p2 = parent2.copy()

        candidates1 = get_all_subtrees(p1, allow_constants=False, min_depth=1)
        candidates2 = get_all_subtrees(p2, allow_constants=False, min_depth=1)

        if not candidates1 or not candidates2:
            continue

        subtree1 = random.choice(candidates1)
        subtree2 = random.choice(candidates2)

        # Avoid swapping constants or flat expressions
        if subtree1.depth() < 1 or subtree2.depth() < 1:
            continue

        # Type check: swap only similar arity
        arity1 = 2 if subtree1.left and subtree1.right else 1 if subtree1.left else 0
        arity2 = 2 if subtree2.left and subtree2.right else 1 if subtree2.left else 0
        if arity1 != arity2:
            continue

        # Perform safe subtree replacement
        new_tree1 = safe_replace(p1, subtree1, subtree2)
        new_tree2 = safe_replace(p2, subtree2, subtree1)
        return new_tree1.simplify(), new_tree2.simplify()

    # Fallback to returning parents if all attempts fail
    return parent1.copy(), parent2.copy()

import numpy as np

# Target function
def target_function(x):
    return x+10000

# Generate training data
X = np.linspace(-5, 5, 50)
Y = target_function(X)

# Fitness: Mean Squared Error (MSE)
def evaluate_fitness(expr, X, Y):
    errors = []
    for x_val, y_true in zip(X, Y):
        y_pred = expr.evaluate({'x': x_val})
        if np.isnan(y_pred) or np.isinf(y_pred):
            return float('inf')  # bad expressions get high penalty
        errors.append((y_true - y_pred) ** 2)
    return np.mean(errors)

# Main training loop
def evolve_symbolic_expression(
    generations=50,
    population_size=50,
    mutation_rate=0.2,
    tournament_size=5
):
    # 1. Initialize population
    population = [generate_random_tree(max_depth=3) for _ in range(population_size)]

    for gen in range(generations):
        # 2. Evaluate fitness
        fitness_scores = [evaluate_fitness(ind, X, Y) for ind in population]

        # 3. Report best
        best_idx = np.argmin(fitness_scores)
        best_expr = population[best_idx]
        best_mse = fitness_scores[best_idx]
        print(f"Gen {gen:02d} | Best MSE: {best_mse:.4f} | Expression: {best_expr.to_string()}")

        # 4. Selection (Tournament)
        new_population = []
        while len(new_population) < population_size:
            # Select parents
            def tournament():
                contenders = random.sample(list(zip(population, fitness_scores)), tournament_size)
                return min(contenders, key=lambda x: x[1])[0]

            parent1 = tournament()
            parent2 = tournament()

            # Crossover
            child1, child2 = crossover(parent1, parent2)

            # Mutation
            child1 = mutate(child1, mutation_rate=mutation_rate)
            child2 = mutate(child2, mutation_rate=mutation_rate)

            new_population.extend([child1, child2])

        population = new_population[:population_size]

    # Final best
    final_best_idx = np.argmin([evaluate_fitness(ind, X, Y) for ind in population])
    final_best = population[final_best_idx]
    return final_best

# Run
best_tree = evolve_symbolic_expression()
print(f"\n🎯 Final Best Expression: {best_tree.to_string()}")

# 🚀 Here’s a Smart Roadmap for Your Next Steps
# 🔹 1. Expression Generation & Mutation (for Symbolic Regression)
# You need to generate random expression trees and mutate/crossover them to evolve expressions.

# ✅ Already using something like generate_random_tree()

# ➕ Add smart mutation (change constants, operators, subtrees)

# ➕ Add crossover (swap subtrees between two parents)

# 🔹 2. Fitness Evaluation (for Training/Evolution)
# Given a dataset (X, y):

# Evaluate each expression on X

# Compare output vs y using a loss function (like MSE)
# ➕ Add selection strategy (e.g. tournament, roulette wheel)


# 🔹 3. Gradient-Based Constant Optimization (Symbolic Tuning)
# 🔹 4. Bias Term Support (if not yet included)
# ➕ Run genetic evolution loop:

# Selection → Crossover → Mutation → Evaluation → Elitism
# Elitism support

# Tournament or roulette selection

# Expression complexity penalty

# Gradient-assisted mutation enhancement

def compute_fitness(
    tree,
    X,
    y,
    error_func='mse',
    complexity_penalty=True,
    alpha=0.01,
    complexity_func='depth',
    safe=True
):
    """
    Generalized fitness evaluation for symbolic regression.

    Parameters:
        tree: Symbolic expression tree
        X: Input data
        y: Target output
        error_func: 'mse', 'mae', or custom callable
        complexity_penalty: Apply model complexity penalty
        alpha: Weight for complexity penalty
        complexity_func: 'node_count', 'depth', or custom callable
        safe: Return -inf for invalid trees

    Returns:
        Fitness score (higher is better)
    """
    try:
        y_pred = tree.evaluate(X)
        if safe and (np.any(np.isnan(y_pred)) or np.any(np.isinf(y_pred))):
            return -np.inf
    except:
        return -np.inf

    # Compute error
    if error_func == 'mse':
        error = np.mean((y - y_pred) ** 2)
    elif error_func == 'mae':
        error = np.mean(np.abs(y - y_pred))
    elif callable(error_func):
        error = error_func(y, y_pred)
    else:
        raise ValueError("Unknown error function")

    # Compute complexity penalty
    penalty = 0
    if complexity_penalty:
        if complexity_func == 'node_count':
            penalty = tree.count_nodes()
        elif complexity_func == 'depth':
            penalty = tree.depth()
        elif callable(complexity_func):
            penalty = complexity_func(tree)
        else:
            raise ValueError("Unknown complexity function")

    return -error - alpha * penalty

import numpy as np

def apply_fitness_sharing(
    population,
    fitnesses,
    X,
    similarity_func='structure',  # 'prediction', 'structure', or custom callable
    structure_method='node_overlap',  # 'node_overlap' or other methods
    sigma=0.1,
    alpha=1.0,
    mode='sharing',  # 'sharing' or 'niching'
    normalize=True,
    use_cache=True
):
    """
    Applies fitness sharing or niching to promote population diversity.

    Parameters:
        population: list of trees
        fitnesses: raw fitness scores
        X: input data
        similarity_func: 'prediction', 'structure', or a custom callable
        structure_method: structure similarity measure (e.g., 'node_overlap')
        sigma: bandwidth for similarity decay
        alpha: shape parameter
        mode: 'sharing' (fitness penalty) or 'niching' (niche detection)
        normalize: whether to normalize similarities
        use_cache: avoid duplicate evaluate(X) calls

    Returns:
        Adjusted fitness list (for sharing) or niche densities (for niching)
    """
    n = len(population)
    pred_cache = [None] * n if use_cache else None

    def get_prediction(i):
        if pred_cache[i] is None:
            pred_cache[i] = population[i].evaluate(X)
        return pred_cache[i]

    def prediction_similarity(i, j):
        pred_i = get_prediction(i)
        pred_j = get_prediction(j)
        return np.mean(np.abs(pred_i - pred_j))

    def structure_similarity(i, j):
        sig_i = population[i].get_node_signatures()
        sig_j = population[j].get_node_signatures()
        overlap = len(sig_i & sig_j)
        union = len(sig_i | sig_j)
        if union == 0:
            return 0.0
        return 1.0 - overlap / union  # 0 = same, 1 = disjoint

    if callable(similarity_func):
        similarity = similarity_func
    elif similarity_func == 'prediction':
        similarity = prediction_similarity
    elif similarity_func == 'structure':
        similarity = structure_similarity
    else:
        raise ValueError("Unknown similarity_func")

    adjusted = []
    for i in range(n):
        sharing_sum = 0
        for j in range(n):
            if i == j:
                continue
            sim = similarity(i, j)
            if normalize:
                sim = sim / (sim + 1e-6)  # optional normalization
            sh = max(0, 1 - (sim / sigma) ** alpha)
            sharing_sum += sh

        if mode == 'sharing':
            sharing_factor = max(1, sharing_sum)
            adjusted.append(fitnesses[i] / sharing_factor)
        elif mode == 'niching':
            adjusted.append(sharing_sum)
        else:
            raise ValueError("Unknown mode")

    return adjusted

from collections import defaultdict

def compute_structure_similarity(tree1, tree2, method='node_overlap'):
    if method == 'node_overlap':
        nodes1 = set(tree1.get_node_signatures())
        nodes2 = set(tree2.get_node_signatures())
        intersection = len(nodes1 & nodes2)
        union = len(nodes1 | nodes2)
        return 1 - (intersection / union)  # smaller means more similar
    elif method == 'edit_distance':
        return tree1.tree_edit_distance(tree2)  # You must implement this
    else:
        raise ValueError("Unknown structural similarity method")

def apply_fitness_sharing(
    population,
    fitnesses,
    X,
    similarity_func='prediction',  # or 'structure'
    sigma=0.1,
    alpha=1.0,
    mode='sharing',  # or 'niching'
    structure_method='node_overlap',
    normalize=True,
    use_cache=True
):
    """
    Applies fitness sharing or niching for diversity.

    Parameters:
        population: list of trees
        fitnesses: raw fitness scores
        X: Input data
        similarity_func: 'prediction', 'structure', or custom callable
        sigma: similarity bandwidth
        alpha: sharing shape factor
        mode: 'sharing' (penalize fitness) or 'niching' (detect niches)
        structure_method: 'node_overlap', 'edit_distance'
        normalize: normalize similarities to [0, 1]
        use_cache: whether to cache evaluate(X) results
    """
    shared = []
    prediction_cache = {}

    for i, fit_i in enumerate(fitnesses):
        sharing_sum = 0
        for j, tree_j in enumerate(population):
            if i == j:
                continue

            if similarity_func == 'prediction':
                if use_cache:
                    if i not in prediction_cache:
                        prediction_cache[i] = population[i].evaluate(X)
                    if j not in prediction_cache:
                        prediction_cache[j] = tree_j.evaluate(X)
                    y_i = prediction_cache[i]
                    y_j = prediction_cache[j]
                else:
                    y_i = population[i].evaluate(X)
                    y_j = tree_j.evaluate(X)
                sim = np.mean(np.abs(y_i - y_j))
            elif similarity_func == 'structure':
                sim = compute_structure_similarity(population[i], tree_j, method=structure_method)
            elif callable(similarity_func):
                sim = similarity_func(population[i], tree_j, X)
            else:
                raise ValueError("Unknown similarity function")

            if normalize:
                sim = np.clip(sim / sigma, 0, 1)

            sh = max(0, 1 - sim ** alpha)
            sharing_sum += sh

        shared_factor = max(1, sharing_sum)
        if mode == 'sharing':
            shared.append(fit_i / shared_factor)
        elif mode == 'niching':
            shared.append(shared_factor)  # or use this to define niche density
        else:
            raise ValueError("Unknown sharing mode")

    return shared



