# -*- coding: utf-8 -*-
"""Untitled87.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pWxHR0KRSAB_5J94Vwv-yTRVLlnYPJ1O
"""

import numpy as np
import random

class TrainableNeuron:
    def __init__(self, num_inputs=10, learning_rate=0.01):
        self.num_inputs = num_inputs
        # Randomly initialize weights for different operations
        self.weights = {
            "add": np.random.randn(),
            "sub": np.random.randn(),
            "mul": np.random.randn(),
            "div": np.random.randn()
        }
        self.learning_rate = learning_rate

    def forward(self, inputs):
        if len(inputs) != self.num_inputs:
            raise ValueError(f"Expected {self.num_inputs} inputs, but got {len(inputs)}")

        # Compute a weighted sum of different arithmetic operations
        result = (self.weights["add"] * sum(inputs) +
                  self.weights["sub"] * sum(-x for x in inputs) +
                  self.weights["mul"] * np.prod(inputs) +
                  self.weights["div"] * sum(x for x in inputs if x != 0))  # Avoid division by zero

        return result

    def train(self, inputs, desired_output, epochs=1000):
        """Train the neuron to adjust weights based on error."""
        for _ in range(epochs):
            prediction = self.forward(inputs)
            error = prediction - desired_output

            # Gradient update (simple delta rule)
            self.weights["add"] -= self.learning_rate * error
            self.weights["sub"] -= self.learning_rate * error
            self.weights["mul"] -= self.learning_rate * error
            self.weights["div"] -= self.learning_rate * error

    def get_weights(self):
        return self.weights

# Example Usage
if __name__ == "__main__":
    neuron = TrainableNeuron(num_inputs=10)

    inputs = np.random.uniform(-10, 10, 10)
    desired_output = sum(inputs)  # We want it to learn addition

    # Train the model
    neuron.train(inputs, desired_output, epochs=5000)

    output = neuron.forward(inputs)
    print(f"Inputs: {inputs}")
    print(f"Predicted Output: {output}")
    print(f"Desired Output: {desired_output}")
    print(f"Learned Weights: {neuron.get_weights()}")

import random
import numpy as np

# Define available operations
operations = ["+", "-", "*", "/"]

class GeneticNeuron:
    def __init__(self, num_inputs, population_size=100, mutation_rate=0.2, generations=500):
        self.num_inputs = num_inputs
        self.population_size = population_size
        self.mutation_rate = mutation_rate
        self.generations = generations

    def apply_operations(self, inputs, operation_sequence):
        """Apply the arithmetic sequence to the inputs."""
        result = inputs[0]
        for i in range(1, len(inputs)):
            op = operation_sequence[i - 1]
            if op == "+":
                result += inputs[i]
            elif op == "-":
                result -= inputs[i]
            elif op == "*":
                result *= inputs[i]
            elif op == "/" and inputs[i] != 0:
                result /= inputs[i]  # Avoid division by zero
        return result

    def fitness(self, inputs, operation_sequence, target_output):
        """Compute fitness as the inverse of the absolute error."""
        result = self.apply_operations(inputs, operation_sequence)
        error = abs(result - target_output)
        return 1 / (error + 1e-6)  # Avoid division by zero

    def generate_population(self):
        """Generate a random population of operation sequences."""
        return [[random.choice(operations) for _ in range(self.num_inputs - 1)] for _ in range(self.population_size)]

    def select_parents(self, population, inputs, target_output):
        """Select the top individuals based on fitness."""
        scored_population = [(seq, self.fitness(inputs, seq, target_output)) for seq in population]
        scored_population.sort(key=lambda x: x[1], reverse=True)  # Sort by highest fitness
        return [seq for seq, _ in scored_population[: self.population_size // 2]]  # Keep top 50%

    def crossover(self, parent1, parent2):
        """Perform crossover between two parents."""
        crossover_point = random.randint(1, len(parent1) - 1)
        return parent1[:crossover_point] + parent2[crossover_point:]

    def mutate(self, sequence):
        """Randomly mutate an operation in the sequence."""
        if random.random() < self.mutation_rate:
            mutation_idx = random.randint(0, len(sequence) - 1)
            sequence[mutation_idx] = random.choice(operations)
        return sequence

    def evolve(self, inputs, target_output):
        """Run the genetic algorithm to find the best operation sequence."""
        population = self.generate_population()

        for generation in range(self.generations):
            selected_parents = self.select_parents(population, inputs, target_output)
            new_population = []

            # Create next generation
            while len(new_population) < self.population_size:
                parent1, parent2 = random.sample(selected_parents, 2)
                child = self.crossover(parent1, parent2)
                child = self.mutate(child)
                new_population.append(child)

            population = new_population

            # Display progress every 50 generations
            if generation % 50 == 0:
                best_seq = selected_parents[0]
                best_result = self.apply_operations(inputs, best_seq)
                print(f"Gen {generation}: Best Seq = {best_seq}, Output = {best_result}, Target = {target_output}")

        # Return the best sequence found
        best_seq = self.select_parents(population, inputs, target_output)[0]
        return best_seq

# Example Usage
if __name__ == "__main__":
    num_inputs = 5  # Number of inputs
    inputs = np.random.uniform(1, 10, num_inputs)  # Random numbers between 1 and 10
    target_output = sum(inputs)  # The desired result (e.g., sum of inputs)

    neuron = GeneticNeuron(num_inputs=num_inputs)
    best_operations = neuron.evolve(inputs, target_output)

    print(f"\nFinal Best Operation Sequence: {best_operations}")
    print(f"Final Computed Output: {neuron.apply_operations(inputs, best_operations)}")
    print(f"Desired Output: {target_output}")

import random
import numpy as np

# Define available operations
operations = ["+", "-", "*", "/"]

class Node:
    """Class for a node in the expression tree"""
    def __init__(self, value):
        self.value = value  # Operator or number
        self.left = None
        self.right = None

    def evaluate(self):
        """Recursively evaluate the expression tree"""
        if isinstance(self.value, (int, float)):  # If it's a number, return it
            return self.value

        # Evaluate left and right subtrees
        left_value = self.left.evaluate() if self.left else 0
        right_value = self.right.evaluate() if self.right else 1  # Avoid division by zero

        # Apply the operation
        if self.value == "+":
            return left_value + right_value
        elif self.value == "-":
            return left_value - right_value
        elif self.value == "*":
            return left_value * right_value
        elif self.value == "/" and right_value != 0:
            return left_value / right_value
        return left_value  # Default case (should not happen)

    def __str__(self):
        """Return the string representation of the expression tree"""
        if isinstance(self.value, (int, float)):
            return str(self.value)
        left_str = f"({self.left})" if self.left else ""
        right_str = f"({self.right})" if self.right else ""
        return f"{left_str} {self.value} {right_str}"

class GeneticExpressionTree:
    def __init__(self, num_inputs, population_size=100, mutation_rate=0.2, generations=500):
        self.num_inputs = num_inputs
        self.population_size = population_size
        self.mutation_rate = mutation_rate
        self.generations = generations

    def generate_random_tree(self, inputs):
        """Generate a random expression tree from input values"""
        if len(inputs) == 1:
            return Node(inputs[0])  # Base case: single input

        # Pick a random operator
        operator = random.choice(operations)

        # Split inputs into two groups
        split = random.randint(1, len(inputs) - 1)
        left_inputs = inputs[:split]
        right_inputs = inputs[split:]

        # Create tree nodes
        root = Node(operator)
        root.left = self.generate_random_tree(left_inputs)
        root.right = self.generate_random_tree(right_inputs)

        return root

    def fitness(self, tree, target_output):
        """Compute fitness as inverse of absolute error"""
        result = tree.evaluate()
        error = abs(result - target_output)
        return 1 / (error + 1e-6)  # Avoid division by zero

    def generate_population(self, inputs):
        """Generate an initial random population of expression trees"""
        return [self.generate_random_tree(inputs) for _ in range(self.population_size)]

    def select_parents(self, population, target_output):
        """Select the best individuals based on fitness"""
        scored_population = [(tree, self.fitness(tree, target_output)) for tree in population]
        scored_population.sort(key=lambda x: x[1], reverse=True)  # Sort by highest fitness
        return [tree for tree, _ in scored_population[: self.population_size // 2]]  # Keep top 50%

    def crossover(self, parent1, parent2):
        """Perform crossover by swapping subtrees"""
        if random.random() < 0.5:
            return parent1  # 50% chance to just return the parent unchanged

        new_tree = Node(parent1.value)
        new_tree.left = parent1.left if random.random() < 0.5 else parent2.left
        new_tree.right = parent1.right if random.random() < 0.5 else parent2.right
        return new_tree

    def mutate(self, tree):
        """Randomly mutate an operator or swap a subtree"""
        if random.random() < self.mutation_rate:
            if isinstance(tree.value, str):  # It's an operator, mutate it
                tree.value = random.choice(operations)
            elif tree.left and random.random() < 0.5:
                tree.left = self.mutate(tree.left)
            elif tree.right:
                tree.right = self.mutate(tree.right)
        return tree

    def evolve(self, inputs, target_output):
        """Run the genetic algorithm to find the best expression tree"""
        population = self.generate_population(inputs)

        for generation in range(self.generations):
            selected_parents = self.select_parents(population, target_output)
            new_population = []

            # Create next generation
            while len(new_population) < self.population_size:
                parent1, parent2 = random.sample(selected_parents, 2)
                child = self.crossover(parent1, parent2)
                child = self.mutate(child)
                new_population.append(child)

            population = new_population

            # Display progress every 50 generations
            if generation % 50 == 0:
                best_tree = selected_parents[0]
                best_result = best_tree.evaluate()
                print(f"Gen {generation}: Best Expr = {best_tree}, Output = {best_result}, Target = {target_output}")

        # Return the best expression found
        best_tree = self.select_parents(population, target_output)[0]
        return best_tree

# Example Usage
if __name__ == "__main__":
    num_inputs = 5  # Number of inputs
    inputs = np.random.uniform(1, 10, num_inputs)  # Random numbers between 1 and 10
    target_output = sum(inputs)  # The desired result (e.g., sum of inputs)

    neuron = GeneticExpressionTree(num_inputs=num_inputs)
    best_expression_tree = neuron.evolve(inputs, target_output)

    print(f"\nFinal Best Expression: {best_expression_tree}")
    print(f"Final Computed Output: {best_expression_tree.evaluate()}")
    print(f"Desired Output: {target_output}")

import random
import numpy as np

# Define available arithmetic operations
operations = ["+", "-", "*", "/"]

class Expression:
    """Represents a mathematical expression as a sequence of operations."""
    def __init__(self, sequence=None):
        self.sequence = sequence if sequence else self.generate_random_sequence()

    def generate_random_sequence(self, length=5):
        """Generates a random sequence of arithmetic operations."""
        return [random.choice(operations) for _ in range(length)]

    def evaluate(self, inputs):
        """Applies the arithmetic sequence to the inputs in order."""
        if len(inputs) < 2:
            raise ValueError("At least two inputs are required.")

        result = inputs[0]
        for i in range(1, len(inputs)):
            op = self.sequence[i - 1]  # Select operation from sequence
            if op == "+":
                result += inputs[i]
            elif op == "-":
                result -= inputs[i]
            elif op == "*":
                result *= inputs[i]
            elif op == "/" and inputs[i] != 0:  # Avoid division by zero
                result /= inputs[i]

        return result

    def mutate(self):
        """Randomly changes one of the operations."""
        index = random.randint(0, len(self.sequence) - 1)
        self.sequence[index] = random.choice(operations)

    def crossover(self, other):
        """Performs crossover with another expression."""
        split = random.randint(1, len(self.sequence) - 1)
        new_seq = self.sequence[:split] + other.sequence[split:]
        return Expression(new_seq)

    def __str__(self):
        """Returns a string representation of the operation sequence."""
        return " → ".join(self.sequence)

class GeneticAlgorithm:
    def __init__(self, num_inputs, population_size=100, mutation_rate=0.2, generations=500):
        self.num_inputs = num_inputs
        self.population_size = population_size
        self.mutation_rate = mutation_rate
        self.generations = generations

    def fitness(self, expression, inputs, target_output):
        """Computes fitness based on how close the expression's output is to the target."""
        result = expression.evaluate(inputs)
        error = abs(result - target_output)
        return 1 / (error + 1e-6)  # Avoid division by zero

    def generate_population(self):
        """Creates an initial population of random expressions."""
        return [Expression() for _ in range(self.population_size)]

    def select_parents(self, population, inputs, target_output):
        """Selects the top-performing expressions based on fitness."""
        scored_population = [(expr, self.fitness(expr, inputs, target_output)) for expr in population]
        scored_population.sort(key=lambda x: x[1], reverse=True)  # Sort by highest fitness
        return [expr for expr, _ in scored_population[: self.population_size // 2]]  # Keep top 50%

    def evolve(self, inputs, target_output):
        """Runs the genetic algorithm to evolve the best arithmetic sequence."""
        population = self.generate_population()

        for generation in range(self.generations):
            selected_parents = self.select_parents(population, inputs, target_output)
            new_population = []

            # Create next generation
            while len(new_population) < self.population_size:
                parent1, parent2 = random.sample(selected_parents, 2)
                child = parent1.crossover(parent2)
                if random.random() < self.mutation_rate:
                    child.mutate()
                new_population.append(child)

            population = new_population

            # Display progress every 50 generations
            if generation % 50 == 0:
                best_expr = selected_parents[0]
                best_result = best_expr.evaluate(inputs)
                print(f"Gen {generation}: Best Seq = {best_expr}, Output = {best_result}, Target = {target_output}")

        # Return the best expression found
        best_expr = self.select_parents(population, inputs, target_output)[0]
        return best_expr

# Example Usage
if __name__ == "__main__":
    num_inputs = 5  # Number of inputs
    inputs = np.random.uniform(1, 10, num_inputs)  # Random numbers between 1 and 10
    target_output = sum(inputs)  # The desired result (e.g., sum of inputs)

    ga = GeneticAlgorithm(num_inputs=num_inputs)
    best_expression = ga.evolve(inputs, target_output)

    print(f"\nFinal Best Sequence: {best_expression}")
    print(f"Final Computed Output: {best_expression.evaluate(inputs)}")
    print(f"Desired Output: {target_output}")

import random
import numpy as np

# Define available arithmetic operations
operations = ["+", "-", "*", "/"]

# List of possible target objectives
TARGET_TYPES = {
    "sum": lambda x: sum(x),
    "mean": lambda x: np.mean(x),
    "median": lambda x: np.median(x),
    "std": lambda x: np.std(x),
    "variance": lambda x: np.var(x)
}

class Expression:
    """Represents a mathematical expression as a sequence of operations."""
    def __init__(self, sequence=None):
        self.sequence = sequence if sequence else self.generate_random_sequence()

    def generate_random_sequence(self, length=5):
        """Generates a random sequence of arithmetic operations."""
        return [random.choice(operations) for _ in range(length)]

    def evaluate(self, inputs):
        """Applies the arithmetic sequence to the inputs in order."""
        if len(inputs) < 2:
            raise ValueError("At least two inputs are required.")

        result = inputs[0]
        for i in range(1, len(inputs)):
            op = self.sequence[i - 1]  # Select operation from sequence
            if op == "+":
                result += inputs[i]
            elif op == "-":
                result -= inputs[i]
            elif op == "*":
                result *= inputs[i]
            elif op == "/" and inputs[i] != 0:  # Avoid division by zero
                result /= inputs[i]

        return result

    def mutate(self):
        """Randomly changes one of the operations."""
        index = random.randint(0, len(self.sequence) - 1)
        self.sequence[index] = random.choice(operations)

    def crossover(self, other):
        """Performs crossover with another expression."""
        split = random.randint(1, len(self.sequence) - 1)
        new_seq = self.sequence[:split] + other.sequence[split:]
        return Expression(new_seq)

    def __str__(self):
        """Returns a string representation of the operation sequence."""
        return " → ".join(self.sequence)

class GeneticAlgorithm:
    def __init__(self, num_inputs, population_size=100, mutation_rate=0.2, generations=500, target_type="sum"):
        self.num_inputs = num_inputs
        self.population_size = population_size
        self.mutation_rate = mutation_rate
        self.generations = generations
        self.target_type = target_type  # Define which target (mean, median, etc.)

    def fitness(self, expression, inputs):
        """Computes fitness based on how close the expression's output is to the target."""
        target_output = TARGET_TYPES[self.target_type](inputs)
        result = expression.evaluate(inputs)
        error = abs(result - target_output)
        return 1 / (error + 1e-6)  # Avoid division by zero

    def generate_population(self):
        """Creates an initial population of random expressions."""
        return [Expression() for _ in range(self.population_size)]

    def select_parents(self, population, inputs):
        """Selects the top-performing expressions based on fitness."""
        scored_population = [(expr, self.fitness(expr, inputs)) for expr in population]
        scored_population.sort(key=lambda x: x[1], reverse=True)  # Sort by highest fitness
        return [expr for expr, _ in scored_population[: self.population_size // 2]]  # Keep top 50%

    def evolve(self, inputs):
        """Runs the genetic algorithm to evolve the best arithmetic sequence."""
        population = self.generate_population()

        for generation in range(self.generations):
            selected_parents = self.select_parents(population, inputs)
            new_population = []

            # Create next generation
            while len(new_population) < self.population_size:
                parent1, parent2 = random.sample(selected_parents, 2)
                child = parent1.crossover(parent2)
                if random.random() < self.mutation_rate:
                    child.mutate()
                new_population.append(child)

            population = new_population

            # Display progress every 50 generations
            if generation % 50 == 0:
                best_expr = selected_parents[0]
                best_result = best_expr.evaluate(inputs)
                target_output = TARGET_TYPES[self.target_type](inputs)
                print(f"Gen {generation}: Best Seq = {best_expr}, Output = {best_result}, Target = {target_output}")

        # Return the best expression found
        best_expr = self.select_parents(population, inputs)[0]
        return best_expr

# Example Usage
if __name__ == "__main__":
    num_inputs = 5  # Number of inputs
    inputs = np.random.uniform(1, 10, num_inputs)  # Random numbers between 1 and 10
    target_type = "std"  # Change to "median", "std", "variance", etc.

    ga = GeneticAlgorithm(num_inputs=num_inputs, target_type=target_type)
    best_expression = ga.evolve(inputs)

    print(f"\nFinal Best Sequence for {target_type}: {best_expression}")
    print(f"Final Computed Output: {best_expression.evaluate(inputs)}")
    print(f"Desired {target_type.capitalize()}: {TARGET_TYPES[target_type](inputs)}")

import random
import numpy as np

# Define available operations
operations = ["+", "-", "*", "/"]

TARGET_TYPES = {
    "sum": lambda x: sum(x),
    "mean": lambda x: np.mean(x),
    "median": lambda x: np.median(x),
    "std": lambda x: np.std(x),
    "variance": lambda x: np.var(x)
}

class Node:
    """Represents a node in an expression tree."""
    def __init__(self, value=None, left=None, right=None):
        self.value = value  # Operator (+, -, *, /) or operand (number)
        self.left = left  # Left child (sub-expression)
        self.right = right  # Right child (sub-expression)

    def evaluate(self, inputs):
        """Recursively evaluates the expression tree."""
        if isinstance(self.value, (int, float)):
            return self.value  # Return the number

        if self.left is None or self.right is None:
            return 0  # Invalid case (should not happen)

        left_val = self.left.evaluate(inputs)
        right_val = self.right.evaluate(inputs)

        if self.value == "+":
            return left_val + right_val
        elif self.value == "-":
            return left_val - right_val
        elif self.value == "*":
            return left_val * right_val
        elif self.value == "/" and right_val != 0:  # Avoid division by zero
            return left_val / right_val
        return left_val  # Fallback

    def mutate(self):
        """Mutates a random node in the tree."""
        if random.random() < 0.5:
            # Change an operation
            self.value = random.choice(operations)
        else:
            # Swap children (structural mutation)
            self.left, self.right = self.right, self.left

    def crossover(self, other):
        """Swaps subtrees with another expression."""
        if random.random() < 0.5:
            return Node(self.value, self.left, other.right)  # Mix trees
        return Node(other.value, other.left, self.right)

    def __str__(self):
        """Returns the string representation of the tree (with parentheses)."""
        if isinstance(self.value, (int, float)):
            return str(self.value)
        return f"({self.left} {self.value} {self.right})"

class ExpressionTree:
    """Represents a full arithmetic expression tree."""
    def __init__(self, depth=3):
        self.root = self.generate_random_tree(depth)

    def generate_random_tree(self, depth):
        """Generates a random expression tree."""
        if depth == 0:
            return Node(random.uniform(-10, 10))  # Random number

        operation = random.choice(operations)
        return Node(operation, self.generate_random_tree(depth - 1), self.generate_random_tree(depth - 1))

    def evaluate(self, inputs):
        """Evaluates the tree with the given inputs."""
        return self.root.evaluate(inputs)

    def mutate(self):
        """Mutates the tree."""
        self.root.mutate()

    def crossover(self, other):
        """Performs crossover with another tree."""
        return ExpressionTree().from_root(self.root.crossover(other.root))

    def from_root(self, root):
        """Creates a tree from a given root node."""
        self.root = root
        return self

    def __str__(self):
        """Returns string representation of the tree."""
        return str(self.root)

class GeneticAlgorithm:
    def __init__(self, num_inputs, population_size=100, mutation_rate=0.3, generations=500, target_type="sum"):
        self.num_inputs = num_inputs
        self.population_size = population_size
        self.mutation_rate = mutation_rate
        self.generations = generations
        self.target_type = target_type

    def fitness(self, expr, inputs):
        """Computes fitness using Mean Squared Error."""
        target_output = TARGET_TYPES[self.target_type](inputs)
        result = expr.evaluate(inputs)
        return -((result - target_output) ** 2)  # Minimize error

    def generate_population(self):
        """Creates an initial population."""
        return [ExpressionTree(depth=3) for _ in range(self.population_size)]

    def select_parents(self, population, inputs):
        """Tournament Selection."""
        tournament_size = 5
        selected = []
        for _ in range(self.population_size // 2):
            competitors = random.sample(population, tournament_size)
            best = max(competitors, key=lambda expr: self.fitness(expr, inputs))
            selected.append(best)
        return selected

    def evolve(self, inputs):
        """Runs the genetic algorithm."""
        population = self.generate_population()

        for generation in range(self.generations):
            selected_parents = self.select_parents(population, inputs)
            new_population = []

            while len(new_population) < self.population_size:
                parent1, parent2 = random.sample(selected_parents, 2)
                child = parent1.crossover(parent2)

                if random.random() < self.mutation_rate:
                    child.mutate()

                new_population.append(child)

            population = new_population

            if generation % 50 == 0:
                best_expr = selected_parents[0]
                best_result = best_expr.evaluate(inputs)
                target_output = TARGET_TYPES[self.target_type](inputs)
                print(f"Gen {generation}: Best Expr = {best_expr}, Output = {best_result}, Target = {target_output}")

        return self.select_parents(population, inputs)[0]

# Example Usage
if __name__ == "__main__":
    num_inputs = 10
    inputs = np.random.uniform(10, 100, num_inputs)  # Random numbers
    target_type = "mean"  # Change to "mean", "median", etc.

    ga = GeneticAlgorithm(num_inputs=num_inputs, target_type=target_type)
    best_expression = ga.evolve(inputs)

    print(f"\nFinal Best Expression for {target_type}: {best_expression}")
    print(f"Final Computed Output: {best_expression.evaluate(inputs)}")
    print(f"Desired {target_type.capitalize()}: {TARGET_TYPES[target_type](inputs)}")

import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

# Define available operations
operations = ["+", "-", "*", "/"]

TARGET_TYPES = {
    "sum": lambda x: sum(x),
    "mean": lambda x: np.mean(x),
    "median": lambda x: np.median(x),
    "std": lambda x: np.std(x),
    "variance": lambda x: np.var(x)
}

# --- 1. GENETIC ALGORITHM (GA) FOR SYMBOLIC EXPRESSION EVOLUTION ---
class Node:
    """Represents a node in an expression tree."""
    def __init__(self, value=None, left=None, right=None):
        self.value = value  # Operator (+, -, *, /) or operand (number)
        self.left = left  # Left child (sub-expression)
        self.right = right  # Right child (sub-expression)

    def evaluate(self, inputs):
        """Recursively evaluates the expression tree."""
        if isinstance(self.value, (int, float)):
            return self.value  # Return the number

        if self.left is None or self.right is None:
            return 0  # Invalid case (should not happen)

        left_val = self.left.evaluate(inputs)
        right_val = self.right.evaluate(inputs)

        if self.value == "+":
            return left_val + right_val
        elif self.value == "-":
            return left_val - right_val
        elif self.value == "*":
            return left_val * right_val
        elif self.value == "/" and right_val != 0:  # Avoid division by zero
            return left_val / right_val
        return left_val  # Fallback

    def mutate(self):
        """Mutates a random node in the tree."""
        if random.random() < 0.5:
            self.value = random.choice(operations)  # Change an operation
        else:
            self.left, self.right = self.right, self.left  # Swap children

    def crossover(self, other):
        """Swaps subtrees with another expression."""
        if random.random() < 0.5:
            return Node(self.value, self.left, other.right)
        return Node(other.value, other.left, self.right)

    def __str__(self):
        """Returns the string representation of the tree."""
        if isinstance(self.value, (int, float)):
            return str(self.value)
        return f"({self.left} {self.value} {self.right})"

class ExpressionTree:
    """Represents a full arithmetic expression tree."""
    def __init__(self, depth=3):
        self.root = self.generate_random_tree(depth)

    def generate_random_tree(self, depth):
        """Generates a random expression tree."""
        if depth == 0:
            return Node(random.uniform(-10, 10))  # Random number

        operation = random.choice(operations)
        return Node(operation, self.generate_random_tree(depth - 1), self.generate_random_tree(depth - 1))

    def evaluate(self, inputs):
        """Evaluates the tree with the given inputs."""
        return self.root.evaluate(inputs)

    def mutate(self):
        """Mutates the tree."""
        self.root.mutate()

    def crossover(self, other):
        """Performs crossover with another tree."""
        return ExpressionTree().from_root(self.root.crossover(other.root))

    def from_root(self, root):
        """Creates a tree from a given root node."""
        self.root = root
        return self

    def __str__(self):
        """Returns string representation of the tree."""
        return str(self.root)

class GeneticAlgorithm:
    def __init__(self, num_inputs, population_size=50, mutation_rate=0.3, generations=200, target_type="sum"):
        self.num_inputs = num_inputs
        self.population_size = population_size
        self.mutation_rate = mutation_rate
        self.generations = generations
        self.target_type = target_type

    def fitness(self, expr, inputs):
        """Computes fitness using Mean Squared Error."""
        target_output = TARGET_TYPES[self.target_type](inputs)
        result = expr.evaluate(inputs)
        return -((result - target_output) ** 2)  # Minimize error

    def generate_population(self):
        """Creates an initial population."""
        return [ExpressionTree(depth=3) for _ in range(self.population_size)]

    def select_parents(self, population, inputs):
        """Tournament Selection."""
        tournament_size = 5
        selected = []
        for _ in range(self.population_size // 2):
            competitors = random.sample(population, tournament_size)
            best = max(competitors, key=lambda expr: self.fitness(expr, inputs))
            selected.append(best)
        return selected

    def evolve(self, inputs):
        """Runs the genetic algorithm."""
        population = self.generate_population()

        for generation in range(self.generations):
            selected_parents = self.select_parents(population, inputs)
            new_population = []

            while len(new_population) < self.population_size:
                parent1, parent2 = random.sample(selected_parents, 2)
                child = parent1.crossover(parent2)

                if random.random() < self.mutation_rate:
                    child.mutate()

                new_population.append(child)

            population = new_population

            if generation % 50 == 0:
                best_expr = selected_parents[0]
                print(f"Gen {generation}: Best Expr = {best_expr}")

        return self.select_parents(population, inputs)[0]

# --- 2. NEURAL NETWORK TO OPTIMIZE ARITHMETIC COMBINATIONS ---
class ArithmeticNN(nn.Module):
    def __init__(self):
        super(ArithmeticNN, self).__init__()
        self.weights = nn.Parameter(torch.randn(4))  # 4 weights for +, -, *, /

    def forward(self, x):
        add = x.sum(dim=1) * self.weights[0]
        sub = x.sum(dim=1) * self.weights[1]
        mul = x.prod(dim=1) * self.weights[2]
        div = (x.prod(dim=1) / (x.sum(dim=1) + 1e-6)) * self.weights[3]  # Avoid div by 0
        return add + sub + mul + div

def train_nn(best_expression, inputs, target_type):
    inputs_tensor = torch.tensor(inputs, dtype=torch.float32).unsqueeze(0)  # Convert inputs
    target_output = torch.tensor(TARGET_TYPES[target_type](inputs), dtype=torch.float32)

    model = ArithmeticNN()
    optimizer = optim.Adam(model.parameters(), lr=0.01)
    loss_fn = nn.MSELoss()

    for epoch in range(1000):
        optimizer.zero_grad()
        output = model(inputs_tensor)
        loss = loss_fn(output, target_output)
        loss.backward()
        optimizer.step()

        if epoch % 100 == 0:
            print(f"Epoch {epoch}: Loss = {loss.item()}")

    return model

# --- 3. RUNNING THE HYBRID MODEL ---
if __name__ == "__main__":
    num_inputs = 5
    inputs = np.random.uniform(1, 10, num_inputs)
    target_type = "mean"

    ga = GeneticAlgorithm(num_inputs=num_inputs, target_type=target_type)
    best_expression = ga.evolve(inputs)
    nn_model = train_nn(best_expression, inputs, target_type)

    print("\nFinal Optimized Expression Weights:", nn_model.weights.data.numpy())